/**
 * 문제문 프레임 28종 × 11개 언어.
 *
 * 이 앱은 "영어를 배우는 앱"이므로 어느 언어에서든 **영어 단어(%1$s)는 그대로**
 * 남고, 그 주변 문장만 학습자의 언어로 바뀐다.
 *
 * 13~17번(…를 영어로?)은 인자가 한국어 뜻이다. 그림이 있는 문제는 화면이
 * 프레임 대신 "이 그림은 영어로?"(1aa85738)를 쓰므로 실제로는 거의 안 보이지만,
 * 그림이 없는 폴백을 위해 번역해 둔다.
 */
module.exports = {

// ---------- 듣기 ----------
"c8b5801d": { en:"What does the word you heard mean?", ja:"きこえた たんごの いみは?", zh:"听到的单词是什么意思?", es:"¿Qué significa la palabra que oíste?", fr:"Que veut dire le mot entendu ?", de:"Was bedeutet das gehörte Wort?", pt:"O que significa a palavra que você ouviu?", ru:"Что означает услышанное слово?", vi:"Từ vừa nghe nghĩa là gì?", th:"คำที่ได้ยินแปลว่าอะไร?", in:"Apa arti kata yang kamu dengar?" },
"366dec85": { en:"What does the sentence you heard mean?", ja:"きこえた ぶんの いみは?", zh:"听到的句子是什么意思?", es:"¿Qué significa la frase que oíste?", fr:"Que veut dire la phrase entendue ?", de:"Was bedeutet der gehörte Satz?", pt:"O que significa a frase que você ouviu?", ru:"Что означает услышанное предложение?", vi:"Câu vừa nghe nghĩa là gì?", th:"ประโยคที่ได้ยินแปลว่าอะไร?", in:"Apa arti kalimat yang kamu dengar?" },
"4d6281c4": { en:"What did you hear?", ja:"なにが きこえた?", zh:"你听到了什么?", es:"¿Qué oíste?", fr:"Qu'as-tu entendu ?", de:"Was hast du gehört?", pt:"O que você ouviu?", ru:"Что ты услышал?", vi:"Bạn nghe thấy gì?", th:"ได้ยินอะไร?", in:"Apa yang kamu dengar?" },
"c087bfe9": { en:"Which letter did you hear?", ja:"どの アルファベットが きこえた?", zh:"你听到了哪个字母?", es:"¿Qué letra oíste?", fr:"Quelle lettre as-tu entendue ?", de:"Welchen Buchstaben hast du gehört?", pt:"Que letra você ouviu?", ru:"Какую букву ты услышал?", vi:"Bạn nghe thấy chữ cái nào?", th:"ได้ยินตัวอักษรตัวไหน?", in:"Huruf apa yang kamu dengar?" },
"018ef4e1": { en:"In the dialog, what does \"%1$s...\" mean?", ja:"かいわの 中の「%1$s...」の いみは?", zh:"对话中 \"%1$s...\" 这句话是什么意思?", es:"En el diálogo, ¿qué significa \"%1$s...\"?", fr:"Dans le dialogue, que veut dire « %1$s... » ?", de:"Was bedeutet \"%1$s...\" im Dialog?", pt:"No diálogo, o que significa \"%1$s...\"?", ru:"Что означает фраза «%1$s...» из диалога?", vi:"Trong hội thoại, \"%1$s...\" nghĩa là gì?", th:"ในบทสนทนา \"%1$s...\" หมายความว่าอะไร?", in:"Dalam dialog, apa arti \"%1$s...\"?" },

// ---------- 뜻 고르기 ----------
"a933e669": { en:"What does \"%1$s\" mean?", ja:"「%1$s」の いみは?", zh:"\"%1$s\" 是什么意思?", es:"¿Qué significa \"%1$s\"?", fr:"Que veut dire « %1$s » ?", de:"Was bedeutet \"%1$s\"?", pt:"O que significa \"%1$s\"?", ru:"Что означает «%1$s»?", vi:"\"%1$s\" nghĩa là gì?", th:"\"%1$s\" แปลว่าอะไร?", in:"Apa arti \"%1$s\"?" },
"e320ea2b": { en:"What does \"%1$s\" mean?", ja:"「%1$s」は どういう いみ?", zh:"\"%1$s\" 是什么意思呢?", es:"¿Qué querrá decir \"%1$s\"?", fr:"Que peut bien vouloir dire « %1$s » ?", de:"Was heißt wohl \"%1$s\"?", pt:"O que será que \"%1$s\" significa?", ru:"Как думаешь, что значит «%1$s»?", vi:"\"%1$s\" có nghĩa là gì nhỉ?", th:"\"%1$s\" หมายความว่าอย่างไรนะ?", in:"Kira-kira apa arti \"%1$s\"?" },
"12f8c41c": { en:"\"%1$s\"\nWhat does it mean?", ja:"「%1$s」\nどういう いみ?", zh:"\"%1$s\"\n是什么意思?", es:"\"%1$s\"\n¿Qué significa?", fr:"« %1$s »\nQue veut-elle dire ?", de:"\"%1$s\"\nWas bedeutet das?", pt:"\"%1$s\"\nO que significa?", ru:"«%1$s»\nЧто это значит?", vi:"\"%1$s\"\nNghĩa là gì?", th:"\"%1$s\"\nแปลว่าอะไร?", in:"\"%1$s\"\nApa artinya?" },
"55f8727e": { en:"Peep shouted \"%1$s!\" What does it mean?", ja:"ピープが「%1$s!」と さけんだよ。どういう いみ?", zh:"啾啾喊了一声 \"%1$s!\"。是什么意思?", es:"¡Peep gritó \"%1$s!\" ¿Qué significa?", fr:"Peep a crié « %1$s ! ». Qu'est-ce que ça veut dire ?", de:"Peep rief \"%1$s!\" Was bedeutet das?", pt:"Peep gritou \"%1$s!\" O que significa?", ru:"Пип крикнул «%1$s!» Что это значит?", vi:"Peep hét lên \"%1$s!\" Nghĩa là gì?", th:"พีปตะโกนว่า \"%1$s!\" หมายความว่าอะไร?", in:"Peep berteriak \"%1$s!\" Apa artinya?" },
"452676ab": { en:"\"%1$s\" is written on the board. Pick its meaning!", ja:"こくばんに「%1$s」と かいてあるよ。いみを えらぼう!", zh:"黑板上写着 \"%1$s\"。选出它的意思吧!", es:"En la pizarra pone \"%1$s\". ¡Elige su significado!", fr:"« %1$s » est écrit au tableau. Choisis son sens !", de:"An der Tafel steht \"%1$s\". Wähle die Bedeutung!", pt:"\"%1$s\" está escrito no quadro. Escolha o significado!", ru:"На доске написано «%1$s». Выбери значение!", vi:"Trên bảng viết \"%1$s\". Hãy chọn nghĩa của nó!", th:"บนกระดานเขียนว่า \"%1$s\" เลือกความหมายกัน!", in:"Di papan tertulis \"%1$s\". Pilih artinya!" },
"01751329": { en:"The rabbit asked, \"What does %1$s mean?\"", ja:"うさぎが きいたよ。「%1$s って どういう いみ?」", zh:"兔子问: \"%1$s 是什么意思呀?\"", es:"El conejo preguntó: \"¿Qué significa %1$s?\"", fr:"Le lapin a demandé : « Que veut dire %1$s ? »", de:"Der Hase fragte: \"Was bedeutet %1$s?\"", pt:"O coelho perguntou: \"O que significa %1$s?\"", ru:"Кролик спросил: «Что значит %1$s?»", vi:"Thỏ hỏi: \"%1$s nghĩa là gì thế?\"", th:"กระต่ายถามว่า \"%1$s แปลว่าอะไรเหรอ?\"", in:"Kelinci bertanya, \"Apa arti %1$s?\"" },
"98393c1b": { en:"You saw \"%1$s\" in a picture book. What does it mean?", ja:"えほんで「%1$s」を みつけたよ。どういう いみ?", zh:"你在图画书里看到了 \"%1$s\"。是什么意思?", es:"Viste \"%1$s\" en un cuento. ¿Qué significa?", fr:"Tu as vu « %1$s » dans un livre d'images. Que veut-il dire ?", de:"Du hast \"%1$s\" im Bilderbuch gesehen. Was bedeutet es?", pt:"Você viu \"%1$s\" num livro ilustrado. O que significa?", ru:"Ты увидел «%1$s» в книжке с картинками. Что это значит?", vi:"Bạn thấy \"%1$s\" trong truyện tranh. Nghĩa là gì?", th:"เจอคำว่า \"%1$s\" ในหนังสือภาพ แปลว่าอะไร?", in:"Kamu melihat \"%1$s\" di buku bergambar. Apa artinya?" },
"f3b29e08": { en:"Today's word is \"%1$s\"! Can you guess its meaning?", ja:"きょうの たんごは「%1$s」! いみを あててみよう!", zh:"今天的单词是 \"%1$s\"! 猜猜它的意思吧!", es:"¡La palabra de hoy es \"%1$s\"! ¿Adivinas su significado?", fr:"Le mot du jour est « %1$s » ! Devine son sens !", de:"Das Wort des Tages ist \"%1$s\"! Errätst du die Bedeutung?", pt:"A palavra de hoje é \"%1$s\"! Consegue adivinhar o significado?", ru:"Слово дня — «%1$s»! Угадаешь значение?", vi:"Từ hôm nay là \"%1$s\"! Đoán nghĩa xem nào!", th:"คำวันนี้คือ \"%1$s\"! ทายความหมายดูสิ!", in:"Kata hari ini \"%1$s\"! Bisa tebak artinya?" },

// ---------- 그림 고르기 ----------
"375f518e": { en:"Which picture is \"%1$s\"?", ja:"「%1$s」は どの え?", zh:"\"%1$s\" 是哪张图?", es:"¿Qué dibujo es \"%1$s\"?", fr:"Quelle image est « %1$s » ?", de:"Welches Bild ist \"%1$s\"?", pt:"Qual figura é \"%1$s\"?", ru:"Какая картинка — «%1$s»?", vi:"\"%1$s\" là hình nào?", th:"\"%1$s\" คือรูปไหน?", in:"Gambar mana yang \"%1$s\"?" },
"ad76c0d4": { en:"Find \"%1$s\" among the pictures!", ja:"えの 中から「%1$s」を さがそう!", zh:"在图片中找出 \"%1$s\" 吧!", es:"¡Busca \"%1$s\" entre los dibujos!", fr:"Trouve « %1$s » parmi les images !", de:"Finde \"%1$s\" unter den Bildern!", pt:"Encontre \"%1$s\" entre as figuras!", ru:"Найди «%1$s» среди картинок!", vi:"Tìm \"%1$s\" trong các hình!", th:"หา \"%1$s\" จากรูปภาพ!", in:"Cari \"%1$s\" di antara gambar-gambar!" },
"6dc70e58": { en:"Peep is looking for \"%1$s\". Which picture is it?", ja:"ピープが「%1$s」を さがしているよ。どの え?", zh:"啾啾在找 \"%1$s\"。是哪张图呢?", es:"Peep busca \"%1$s\". ¿Qué dibujo es?", fr:"Peep cherche « %1$s ». Quelle image est-ce ?", de:"Peep sucht \"%1$s\". Welches Bild ist es?", pt:"Peep está procurando \"%1$s\". Qual figura é?", ru:"Пип ищет «%1$s». Какая это картинка?", vi:"Peep đang tìm \"%1$s\". Là hình nào nhỉ?", th:"พีปกำลังหา \"%1$s\" คือรูปไหนนะ?", in:"Peep sedang mencari \"%1$s\". Gambar yang mana ya?" },
"a0168b2f": { en:"Pick the picture that matches \"%1$s\".", ja:"「%1$s」に あう えを えらぼう。", zh:"选出和 \"%1$s\" 相配的图。", es:"Elige el dibujo que corresponde a \"%1$s\".", fr:"Choisis l'image qui correspond à « %1$s ».", de:"Wähle das Bild, das zu \"%1$s\" passt.", pt:"Escolha a figura que combina com \"%1$s\".", ru:"Выбери картинку, подходящую к «%1$s».", vi:"Chọn hình phù hợp với \"%1$s\".", th:"เลือกรูปที่เข้ากับ \"%1$s\"", in:"Pilih gambar yang cocok dengan \"%1$s\"." },
"1aa85738": { en:"What is this picture in English?", ja:"この えは えいごで なに?", zh:"这张图用英语怎么说?", es:"¿Cómo se dice este dibujo en inglés?", fr:"Comment dit-on cette image en anglais ?", de:"Was ist dieses Bild auf Englisch?", pt:"Como se diz esta figura em inglês?", ru:"Как это будет по-английски?", vi:"Hình này tiếng Anh là gì?", th:"รูปนี้ภาษาอังกฤษเรียกว่าอะไร?", in:"Gambar ini bahasa Inggrisnya apa?" },

// ---------- 영어로 (인자 = 한국어 뜻 — 그림 폴백용) ----------
"b797909f": { en:"How do you say \"%1$s\" in English?", ja:"「%1$s」は えいごで?", zh:"\"%1$s\" 用英语怎么说?", es:"¿Cómo se dice \"%1$s\" en inglés?", fr:"Comment dit-on « %1$s » en anglais ?", de:"Wie sagt man \"%1$s\" auf Englisch?", pt:"Como se diz \"%1$s\" em inglês?", ru:"Как сказать «%1$s» по-английски?", vi:"\"%1$s\" tiếng Anh nói thế nào?", th:"\"%1$s\" ภาษาอังกฤษพูดว่าอย่างไร?", in:"Bagaimana mengatakan \"%1$s\" dalam bahasa Inggris?" },
"21a6d4b2": { en:"Tell Peep how to say \"%1$s\" in English!", ja:"ピープに「%1$s」を えいごで おしえてあげよう!", zh:"告诉啾啾 \"%1$s\" 的英语说法吧!", es:"¡Dile a Peep cómo se dice \"%1$s\" en inglés!", fr:"Dis à Peep comment dire « %1$s » en anglais !", de:"Sag Peep, wie \"%1$s\" auf Englisch heißt!", pt:"Diga ao Peep como falar \"%1$s\" em inglês!", ru:"Подскажи Пипу, как сказать «%1$s» по-английски!", vi:"Hãy chỉ cho Peep cách nói \"%1$s\" bằng tiếng Anh!", th:"บอกพีปหน่อยว่า \"%1$s\" ภาษาอังกฤษพูดว่าอะไร!", in:"Beritahu Peep cara mengatakan \"%1$s\" dalam bahasa Inggris!" },
"4002700b": { en:"The penguin wonders: what is \"%1$s\" in English?", ja:"ペンギンが しりたがっているよ。「%1$s」は えいごで?", zh:"企鹅很好奇: \"%1$s\" 的英语是什么?", es:"El pingüino se pregunta: ¿cómo es \"%1$s\" en inglés?", fr:"Le pingouin se demande : comment dit-on « %1$s » en anglais ?", de:"Der Pinguin fragt sich: Was heißt \"%1$s\" auf Englisch?", pt:"O pinguim quer saber: como é \"%1$s\" em inglês?", ru:"Пингвину интересно: как будет «%1$s» по-английски?", vi:"Chim cánh cụt thắc mắc: \"%1$s\" tiếng Anh là gì?", th:"เพนกวินสงสัยว่า \"%1$s\" ภาษาอังกฤษคืออะไร?", in:"Penguin penasaran: apa bahasa Inggrisnya \"%1$s\"?" },
"b5f5d7a9": { en:"English time! Pick the English word for \"%1$s\".", ja:"えいごの じかん!「%1$s」の えいごを えらぼう。", zh:"英语时间! 选出 \"%1$s\" 的英语。", es:"¡Hora de inglés! Elige la palabra inglesa para \"%1$s\".", fr:"C'est l'heure d'anglais ! Choisis le mot anglais pour « %1$s ».", de:"Englischzeit! Wähle das englische Wort für \"%1$s\".", pt:"Hora do inglês! Escolha a palavra em inglês para \"%1$s\".", ru:"Урок английского! Выбери английское слово для «%1$s».", vi:"Giờ tiếng Anh! Chọn từ tiếng Anh cho \"%1$s\".", th:"ชั่วโมงภาษาอังกฤษ! เลือกคำภาษาอังกฤษของ \"%1$s\"", in:"Waktunya bahasa Inggris! Pilih kata Inggris untuk \"%1$s\"." },
"b2ecaffb": { en:"Mom asked, \"What is %1$s in English?\"", ja:"ママが きいたよ。「%1$s って えいごで なに?」", zh:"妈妈问: \"%1$s 用英语怎么说?\"", es:"Mamá preguntó: \"¿Cómo es %1$s en inglés?\"", fr:"Maman a demandé : « Comment dit-on %1$s en anglais ? »", de:"Mama fragte: \"Was heißt %1$s auf Englisch?\"", pt:"A mamãe perguntou: \"Como é %1$s em inglês?\"", ru:"Мама спросила: «Как по-английски %1$s?»", vi:"Mẹ hỏi: \"%1$s tiếng Anh là gì?\"", th:"แม่ถามว่า \"%1$s ภาษาอังกฤษว่าอะไร?\"", in:"Ibu bertanya, \"Apa bahasa Inggrisnya %1$s?\"" },

// ---------- 알파벳 · 파닉스 ----------
"2310939c": { en:"%1$s (%2$s)\nWhat is the first letter?", ja:"%1$s (%2$s)\nさいしょの もじは?", zh:"%1$s (%2$s)\n第一个字母是什么?", es:"%1$s (%2$s)\n¿Cuál es la primera letra?", fr:"%1$s (%2$s)\nQuelle est la première lettre ?", de:"%1$s (%2$s)\nWas ist der erste Buchstabe?", pt:"%1$s (%2$s)\nQual é a primeira letra?", ru:"%1$s (%2$s)\nКакая первая буква?", vi:"%1$s (%2$s)\nChữ cái đầu tiên là gì?", th:"%1$s (%2$s)\nตัวอักษรตัวแรกคืออะไร?", in:"%1$s (%2$s)\nApa huruf pertamanya?" },
"20ff9e96": { en:"What is the lowercase of capital %1$s?", ja:"おおもじ %1$s の こもじは?", zh:"大写 %1$s 的小写是什么?", es:"¿Cuál es la minúscula de la mayúscula %1$s?", fr:"Quelle est la minuscule de la majuscule %1$s ?", de:"Wie lautet der Kleinbuchstabe von %1$s?", pt:"Qual é a minúscula da maiúscula %1$s?", ru:"Какая строчная буква у заглавной %1$s?", vi:"Chữ thường của chữ hoa %1$s là gì?", th:"ตัวพิมพ์เล็กของ %1$s คืออะไร?", in:"Apa huruf kecil dari huruf besar %1$s?" },
"887a7a17": { en:"This is a picture of %1$s.\nWhat is the first sound of %2$s?", ja:"%1$s の えだよ。\n%2$s の さいしょの おとは?", zh:"这是%1$s的图。\n%2$s 的第一个音是什么?", es:"Es un dibujo de %1$s.\n¿Cuál es el primer sonido de %2$s?", fr:"C'est une image de %1$s.\nQuel est le premier son de %2$s ?", de:"Das ist ein Bild von %1$s.\nWas ist der erste Laut von %2$s?", pt:"É uma figura de %1$s.\nQual é o primeiro som de %2$s?", ru:"Это картинка %1$s.\nКакой первый звук в %2$s?", vi:"Đây là hình %1$s.\nÂm đầu của %2$s là gì?", th:"นี่คือรูป %1$s\nเสียงแรกของ %2$s คืออะไร?", in:"Ini gambar %1$s.\nApa bunyi pertama dari %2$s?" },
"02bc90d3": { en:"%1$s (%2$s)\nWhat is the middle vowel?", ja:"%1$s (%2$s)\nまんなかの ぼいんは?", zh:"%1$s (%2$s)\n中间的元音是什么?", es:"%1$s (%2$s)\n¿Cuál es la vocal del medio?", fr:"%1$s (%2$s)\nQuelle est la voyelle du milieu ?", de:"%1$s (%2$s)\nWelcher Vokal steht in der Mitte?", pt:"%1$s (%2$s)\nQual é a vogal do meio?", ru:"%1$s (%2$s)\nКакая гласная в середине?", vi:"%1$s (%2$s)\nNguyên âm ở giữa là gì?", th:"%1$s (%2$s)\nสระตรงกลางคืออะไร?", in:"%1$s (%2$s)\nApa vokal di tengahnya?" },

// ---------- 빈칸 예문 ----------
// 한국어 해석 줄(%2$s)을 떨어뜨린다 — 영어 문맥만으로 풀 수 있고, 뜻은 해설에서 배운다
"363ce10c": { en:"%1$s", ja:"%1$s", zh:"%1$s", es:"%1$s", fr:"%1$s", de:"%1$s", pt:"%1$s", ru:"%1$s", vi:"%1$s", th:"%1$s", in:"%1$s" },

};
