/**
 * 트랙·유닛·레슨 **제목** 뼈대 번역.
 * 제목 속 낱말(마을 이름·학년 띠·장면 이름)은 words_i18n.js 사전이 갈아 끼운다.
 * 뼈대 등록·팩 태깅은 tools/i18n/tag_titles.js 가 한다.
 */
module.exports = {

// ---------- 트랙 제목·부제 ----------
t_tr_basic: { en:"Step-by-step Basics", ja:"きそ こつこつ", zh:"基础循序渐进", es:"Bases paso a paso", fr:"Bases pas à pas", de:"Basis Schritt für Schritt", pt:"Básico passo a passo", ru:"База шаг за шагом", vi:"Cơ bản từng bước", th:"พื้นฐานทีละขั้น", in:"Dasar selangkah demi selangkah" },
t_tr_basic_s: { en:"10 stages from elementary to advanced", ja:"しょうがくから じょうきゅうまで 10だんかい", zh:"从小学到高级共10级", es:"10 niveles de primaria a avanzado", fr:"10 paliers du primaire à l'avancé", de:"10 Stufen von Grundschule bis Fortgeschritten", pt:"10 etapas do fundamental ao avançado", ru:"10 ступеней от начальной школы до продвинутого", vi:"10 bậc từ tiểu học đến nâng cao", th:"10 ขั้นจากประถมถึงระดับสูง", in:"10 tahap dari SD sampai mahir" },
t_tr_daily: { en:"Daily & Travel English", ja:"にちじょう · りょこう えいご", zh:"日常·旅行英语", es:"Inglés diario y de viaje", fr:"Anglais quotidien · voyage", de:"Alltags- & Reise-Englisch", pt:"Inglês diário e de viagem", ru:"Повседневный и дорожный английский", vi:"Tiếng Anh hằng ngày · du lịch", th:"อังกฤษชีวิตประจำวัน · ท่องเที่ยว", in:"Inggris harian · perjalanan" },
t_tr_daily_s: { en:"Until the day you travel abroad alone", ja:"ひとりで かいがいりょこうに いく ひまで", zh:"直到独自出国旅行的那天", es:"Hasta el día que viajes solo al extranjero", fr:"Jusqu'au jour où tu voyageras seul", de:"Bis zu deiner ersten Solo-Reise", pt:"Até o dia de viajar sozinho", ru:"До первой самостоятельной поездки", vi:"Đến ngày tự đi du lịch nước ngoài", th:"จนถึงวันที่เที่ยวต่างประเทศคนเดียว", in:"Sampai hari bepergian ke luar negeri sendiri" },
t_tr_elem: { en:"Elementary Playground", ja:"しょうがくえいご あそびば", zh:"小学英语游乐场", es:"Patio de primaria", fr:"Cour de récré du primaire", de:"Grundschul-Spielplatz", pt:"Parquinho do fundamental", ru:"Площадка начальной школы", vi:"Sân chơi tiểu học", th:"สนามเด็กเล่นประถม", in:"Taman bermain SD" },
t_tr_elem_s: { en:"Learn through play, starting from ABC", ja:"ABCから あそびながら まなぼう", zh:"从字母开始边玩边学", es:"Aprende jugando desde el abecedario", fr:"Apprends en jouant dès l'alphabet", de:"Spielend lernen, ab dem ABC", pt:"Aprenda brincando desde o ABC", ru:"Учись играя, начиная с алфавита", vi:"Vừa chơi vừa học từ ABC", th:"เรียนผ่านการเล่นตั้งแต่ ABC", in:"Belajar sambil bermain mulai dari ABC" },
t_tr_grammar: { en:"Grammar Focus", ja:"ぶんぽう しゅうちゅう", zh:"语法专项", es:"Enfoque en gramática", fr:"Spécial grammaire", de:"Grammatik-Fokus", pt:"Foco em gramática", ru:"Упор на грамматику", vi:"Chuyên ngữ pháp", th:"เจาะไวยากรณ์", in:"Fokus tata bahasa" },
t_tr_grammar_s: { en:"From be-verbs to inversion and conditionals", ja:"be どうしから とうち · かていほうまで", zh:"从be动词到倒装·虚拟语气", es:"Del verbo be a inversión y condicionales", fr:"Du verbe be à l'inversion et au conditionnel", de:"Vom be-Verb bis Inversion und Konditional", pt:"Do verbo be à inversão e condicionais", ru:"От глагола be до инверсии и условных", vi:"Từ động từ be đến đảo ngữ · giả định", th:"จากกริยา be ถึงการสลับและเงื่อนไข", in:"Dari kata kerja be sampai inversi dan pengandaian" },
t_tr_listen: { en:"Listening Focus", ja:"リスニング しゅうちゅう", zh:"听力专项", es:"Enfoque en escucha", fr:"Spécial écoute", de:"Hör-Fokus", pt:"Foco em escuta", ru:"Упор на аудирование", vi:"Chuyên luyện nghe", th:"เจาะการฟัง", in:"Fokus menyimak" },
t_tr_listen_s: { en:"Words → sentences → dialogs, train your ears", ja:"たんご→ぶんしょう→かいわで みみを きたえる", zh:"单词→句子→对话，练出好耳朵", es:"Palabras → frases → diálogos, entrena el oído", fr:"Mots → phrases → dialogues, entraîne ton oreille", de:"Wörter → Sätze → Dialoge, Ohren trainieren", pt:"Palavras → frases → diálogos, treine o ouvido", ru:"Слова → фразы → диалоги: тренируй слух", vi:"Từ → câu → hội thoại, luyện đôi tai", th:"คำ→ประโยค→บทสนทนา ฝึกหู", in:"Kata → kalimat → dialog, latih telinga" },
t_tr_reading: { en:"Reading Focus", ja:"どっかい しゅうちゅう", zh:"阅读专项", es:"Enfoque en lectura", fr:"Spécial lecture", de:"Lese-Fokus", pt:"Foco em leitura", ru:"Упор на чтение", vi:"Chuyên đọc hiểu", th:"เจาะการอ่าน", in:"Fokus membaca" },
t_tr_reading_s: { en:"Short texts → practical docs → academic passages", ja:"みじかい ぶん→じつようぶん→がくじゅつぶん", zh:"短文→实用文→学术文章", es:"Textos cortos → prácticos → académicos", fr:"Textes courts → pratiques → académiques", de:"Kurztexte → Gebrauchstexte → Fachtexte", pt:"Textos curtos → práticos → acadêmicos", ru:"Короткие тексты → практические → академические", vi:"Bài ngắn → văn bản thực dụng → học thuật", th:"เรื่องสั้น→เอกสารใช้จริง→บทความวิชาการ", in:"Teks pendek → praktis → akademik" },
t_tr_speak: { en:"Speaking Focus", ja:"スピーキング しゅうちゅう", zh:"口语专项", es:"Enfoque en habla", fr:"Spécial oral", de:"Sprech-Fokus", pt:"Foco em fala", ru:"Упор на говорение", vi:"Chuyên luyện nói", th:"เจาะการพูด", in:"Fokus berbicara" },
t_tr_speak_s: { en:"Open your mouth: real conversation practice", ja:"くちを ひらこう: じっせん かいわ はつおん", zh:"张开嘴：实战会话发音训练", es:"Suelta la lengua: práctica real de conversación", fr:"Ose parler : entraînement réel à l'oral", de:"Mund auf: echtes Konversationstraining", pt:"Solte a voz: prática real de conversação", ru:"Заговори: практика живой речи", vi:"Mở miệng nói: luyện hội thoại thực chiến", th:"เปิดปากพูด: ฝึกสนทนาจริง", in:"Buka suara: latihan percakapan nyata" },
t_tr_toefl: { en:"TOEFL", ja:"TOEFL", zh:"托福 (TOEFL)", es:"TOEFL", fr:"TOEFL", de:"TOEFL", pt:"TOEFL", ru:"TOEFL", vi:"TOEFL", th:"TOEFL", in:"TOEFL" },
t_tr_toefl_s: { en:"Academic reading & listening", ja:"アカデミック どっかい · リスニング", zh:"学术阅读·听力", es:"Lectura y escucha académicas", fr:"Lecture et écoute académiques", de:"Akademisches Lesen & Hören", pt:"Leitura e escuta acadêmicas", ru:"Академическое чтение и аудирование", vi:"Đọc · nghe học thuật", th:"อ่าน·ฟังเชิงวิชาการ", in:"Membaca & menyimak akademik" },
t_tr_toeic: { en:"TOEIC", ja:"TOEIC", zh:"托业 (TOEIC)", es:"TOEIC", fr:"TOEIC", de:"TOEIC", pt:"TOEIC", ru:"TOEIC", vi:"TOEIC", th:"TOEIC", in:"TOEIC" },
t_tr_toeic_s: { en:"Master every part, type by type", ja:"パートべつに ゆうけいを こうりゃく", zh:"分部分攻克各类题型", es:"Domina cada parte, tipo a tipo", fr:"Maîtrise chaque partie, type par type", de:"Jeden Teil Typ für Typ meistern", pt:"Domine cada parte, tipo a tipo", ru:"Освой каждую часть по типам", vi:"Chinh phục từng phần theo dạng", th:"พิชิตทีละพาร์ตทีละแบบ", in:"Kuasai tiap bagian per tipe" },
t_tr_write: { en:"Writing Focus", ja:"ライティング しゅうちゅう", zh:"写作专项", es:"Enfoque en escritura", fr:"Spécial écrit", de:"Schreib-Fokus", pt:"Foco em escrita", ru:"Упор на письмо", vi:"Chuyên luyện viết", th:"เจาะการเขียน", in:"Fokus menulis" },
t_tr_write_s: { en:"Spelling → word order → composition", ja:"スペル→ごじゅん→えいさくぶん", zh:"拼写→语序→写作", es:"Ortografía → orden → redacción", fr:"Orthographe → ordre des mots → rédaction", de:"Rechtschreibung → Wortstellung → Aufsatz", pt:"Ortografia → ordem → redação", ru:"Правописание → порядок слов → сочинение", vi:"Chính tả → trật tự từ → viết câu", th:"สะกด→เรียงคำ→แต่งประโยค", in:"Ejaan → urutan kata → mengarang" },

// ---------- 공용 뼈대 ----------
t_word: { en:"%1$s", ja:"%1$s", zh:"%1$s", es:"%1$s", fr:"%1$s", de:"%1$s", pt:"%1$s", ru:"%1$s", vi:"%1$s", th:"%1$s", in:"%1$s" },
t_stage: { en:"Stage %1$s · %2$s", ja:"だい%1$sだんかい %2$s", zh:"第%1$s级 %2$s", es:"Nivel %1$s · %2$s", fr:"Palier %1$s · %2$s", de:"Stufe %1$s · %2$s", pt:"Etapa %1$s · %2$s", ru:"Ступень %1$s · %2$s", vi:"Bậc %1$s · %2$s", th:"ขั้น %1$s · %2$s", in:"Tahap %1$s · %2$s" },
t_stage_n: { en:"Stage %1$s · %2$s %3$s", ja:"だい%1$sだんかい %2$s %3$s", zh:"第%1$s级 %2$s %3$s", es:"Nivel %1$s · %2$s %3$s", fr:"Palier %1$s · %2$s %3$s", de:"Stufe %1$s · %2$s %3$s", pt:"Etapa %1$s · %2$s %3$s", ru:"Ступень %1$s · %2$s %3$s", vi:"Bậc %1$s · %2$s %3$s", th:"ขั้น %1$s · %2$s %3$s", in:"Tahap %1$s · %2$s %3$s" },
t_lesson: { en:"Lesson %1$s", ja:"レッスン %1$s", zh:"第 %1$s 课", es:"Lección %1$s", fr:"Leçon %1$s", de:"Lektion %1$s", pt:"Lição %1$s", ru:"Урок %1$s", vi:"Bài %1$s", th:"บทที่ %1$s", in:"Pelajaran %1$s" },
t_expr: { en:"%1$s · Phrases", ja:"%1$s · ひょうげん", zh:"%1$s · 表达", es:"%1$s · Frases", fr:"%1$s · Expressions", de:"%1$s · Ausdrücke", pt:"%1$s · Frases", ru:"%1$s · Фразы", vi:"%1$s · Mẫu câu", th:"%1$s · สำนวน", in:"%1$s · Ungkapan" },
t_talk2: { en:"%1$s · Speaking", ja:"%1$s · はなす", zh:"%1$s · 口语", es:"%1$s · Hablar", fr:"%1$s · Oral", de:"%1$s · Sprechen", pt:"%1$s · Fala", ru:"%1$s · Говорение", vi:"%1$s · Nói", th:"%1$s · พูด", in:"%1$s · Bicara" },
t_num: { en:"%1$s %2$s", ja:"%1$s %2$s", zh:"%1$s %2$s", es:"%1$s %2$s", fr:"%1$s %2$s", de:"%1$s %2$s", pt:"%1$s %2$s", ru:"%1$s %2$s", vi:"%1$s %2$s", th:"%1$s %2$s", in:"%1$s %2$s" },

// ---------- 일상·여행 유닛 ----------
t_u_greet: { en:"Greetings & Introductions", ja:"あいさつと じこしょうかい", zh:"问候与介绍", es:"Saludos y presentaciones", fr:"Salutations et présentations", de:"Begrüßung & Vorstellung", pt:"Cumprimentos e apresentações", ru:"Приветствия и знакомство", vi:"Chào hỏi và giới thiệu", th:"ทักทายและแนะนำตัว", in:"Salam dan perkenalan" },
t_u_rest: { en:"At the Restaurant", ja:"レストランで", zh:"在餐厅", es:"En el restaurante", fr:"Au restaurant", de:"Im Restaurant", pt:"No restaurante", ru:"В ресторане", vi:"Ở nhà hàng", th:"ที่ร้านอาหาร", in:"Di restoran" },
t_u_shop: { en:"Shopping", ja:"かいもの", zh:"购物", es:"De compras", fr:"Shopping", de:"Einkaufen", pt:"Compras", ru:"Покупки", vi:"Mua sắm", th:"ช้อปปิ้ง", in:"Belanja" },
t_u_way: { en:"Finding Your Way", ja:"みちを さがす", zh:"找路", es:"Cómo orientarse", fr:"Trouver son chemin", de:"Den Weg finden", pt:"Achando o caminho", ru:"Как найти дорогу", vi:"Tìm đường", th:"หาเส้นทาง", in:"Mencari jalan" },
t_u_air: { en:"Airport & Airplane", ja:"くうこうと ひこうき", zh:"机场与飞机", es:"Aeropuerto y avión", fr:"Aéroport et avion", de:"Flughafen & Flugzeug", pt:"Aeroporto e avião", ru:"Аэропорт и самолёт", vi:"Sân bay và máy bay", th:"สนามบินและเครื่องบิน", in:"Bandara & pesawat" },
t_u_hotel: { en:"At the Hotel", ja:"ホテルで", zh:"在酒店", es:"En el hotel", fr:"À l'hôtel", de:"Im Hotel", pt:"No hotel", ru:"В отеле", vi:"Ở khách sạn", th:"ที่โรงแรม", in:"Di hotel" },
t_u_trans: { en:"Getting Around", ja:"こうつうを つかう", zh:"乘坐交通工具", es:"Transporte", fr:"Se déplacer", de:"Unterwegs", pt:"Transporte", ru:"Транспорт", vi:"Đi lại", th:"การเดินทาง", in:"Transportasi" },
t_u_emerg: { en:"Emergencies", ja:"きんきゅう じたい", zh:"紧急情况", es:"Emergencias", fr:"Urgences", de:"Notfälle", pt:"Emergências", ru:"Экстренные случаи", vi:"Tình huống khẩn cấp", th:"เหตุฉุกเฉิน", in:"Keadaan darurat" },
t_u_small: { en:"Small Talk", ja:"スモールトーク", zh:"闲聊", es:"Charla informal", fr:"Petites conversations", de:"Smalltalk", pt:"Conversa fiada", ru:"Светская беседа", vi:"Chuyện phiếm", th:"คุยเล่น", in:"Obrolan ringan" },
t_u_shop2: { en:"Real Sentence Shop %1$s", ja:"じっせん ぶんしょう ざっかてん %1$s", zh:"实战句子杂货店 %1$s", es:"Tienda de frases reales %1$s", fr:"Boutique de phrases réelles %1$s", de:"Echtsatz-Laden %1$s", pt:"Loja de frases reais %1$s", ru:"Лавка живых фраз %1$s", vi:"Tiệm câu thực chiến %1$s", th:"ร้านประโยคใช้จริง %1$s", in:"Toko kalimat nyata %1$s" },

// ---------- 학년 띠 유닛 ----------
t_g_gram: { en:"%1$s Grammar", ja:"%1$s ぶんぽう", zh:"%1$s 语法", es:"Gramática %1$s", fr:"Grammaire %1$s", de:"%1$s Grammatik", pt:"Gramática %1$s", ru:"Грамматика: %1$s", vi:"Ngữ pháp %1$s", th:"ไวยากรณ์ %1$s", in:"Tata bahasa %1$s" },
t_g_listen: { en:"Ear Training · %1$s %2$s", ja:"みみトレ · %1$s %2$s", zh:"磨耳朵 · %1$s %2$s", es:"Entrena el oído · %1$s %2$s", fr:"Entraîne l'oreille · %1$s %2$s", de:"Ohrentraining · %1$s %2$s", pt:"Treino de ouvido · %1$s %2$s", ru:"Тренировка слуха · %1$s %2$s", vi:"Luyện tai · %1$s %2$s", th:"ฝึกหู · %1$s %2$s", in:"Latihan telinga · %1$s %2$s" },
t_g_read: { en:"%1$s Reading %2$s", ja:"%1$s どっかい %2$s", zh:"%1$s 阅读 %2$s", es:"Lectura %1$s %2$s", fr:"Lecture %1$s %2$s", de:"%1$s Lesen %2$s", pt:"Leitura %1$s %2$s", ru:"Чтение: %1$s %2$s", vi:"Đọc hiểu %1$s %2$s", th:"การอ่าน %1$s %2$s", in:"Membaca %1$s %2$s" },
t_g_speak: { en:"Speak Up · %1$s %2$s", ja:"くちトレ · %1$s %2$s", zh:"开口说 · %1$s %2$s", es:"Suelta la lengua · %1$s %2$s", fr:"Ose parler · %1$s %2$s", de:"Sprich los · %1$s %2$s", pt:"Solte a voz · %1$s %2$s", ru:"Заговори · %1$s %2$s", vi:"Mở miệng nói · %1$s %2$s", th:"เปิดปากพูด · %1$s %2$s", in:"Buka suara · %1$s %2$s" },
t_g_write: { en:"Spelling Practice · %1$s %2$s", ja:"スペルれんしゅう · %1$s %2$s", zh:"拼写练习 · %1$s %2$s", es:"Ortografía · %1$s %2$s", fr:"Orthographe · %1$s %2$s", de:"Rechtschreibübung · %1$s %2$s", pt:"Ortografia · %1$s %2$s", ru:"Правописание · %1$s %2$s", vi:"Luyện chính tả · %1$s %2$s", th:"ฝึกสะกด · %1$s %2$s", in:"Latihan ejaan · %1$s %2$s" },

// ---------- 단독 패턴 유닛 ----------
t_s_gramtoeic: { en:"Real Grammar (TOEIC style) %1$s", ja:"じっせん ぶんぽう (TOEIC がた) %1$s", zh:"实战语法 (托业型) %1$s", es:"Gramática real (estilo TOEIC) %1$s", fr:"Grammaire réelle (style TOEIC) %1$s", de:"Praxisgrammatik (TOEIC-Stil) %1$s", pt:"Gramática real (estilo TOEIC) %1$s", ru:"Практическая грамматика (стиль TOEIC) %1$s", vi:"Ngữ pháp thực chiến (kiểu TOEIC) %1$s", th:"ไวยากรณ์ใช้จริง (แนว TOEIC) %1$s", in:"Tata bahasa nyata (gaya TOEIC) %1$s" },
t_s_dict: { en:"Sentence Dictation %1$s", ja:"ぶんしょう かきとり %1$s", zh:"句子听写 %1$s", es:"Dictado de frases %1$s", fr:"Dictée de phrases %1$s", de:"Satzdiktat %1$s", pt:"Ditado de frases %1$s", ru:"Диктант предложений %1$s", vi:"Chính tả câu %1$s", th:"เขียนตามคำบอกประโยค %1$s", in:"Dikte kalimat %1$s" },
t_s_dialog: { en:"Dialog Listening %1$s", ja:"かいわ リスニング %1$s", zh:"对话听力训练 %1$s", es:"Escucha de diálogos %1$s", fr:"Écoute de dialogues %1$s", de:"Dialog-Hören %1$s", pt:"Escuta de diálogos %1$s", ru:"Аудирование диалогов %1$s", vi:"Nghe hội thoại %1$s", th:"ฝึกฟังบทสนทนา %1$s", in:"Menyimak dialog %1$s" },
t_s_pract: { en:"Practical Reading %1$s", ja:"じつようぶん どっかい %1$s", zh:"实用文阅读 %1$s", es:"Lectura práctica %1$s", fr:"Lecture pratique %1$s", de:"Gebrauchstexte lesen %1$s", pt:"Leitura prática %1$s", ru:"Практическое чтение %1$s", vi:"Đọc văn bản thực dụng %1$s", th:"อ่านเอกสารใช้จริง %1$s", in:"Membaca praktis %1$s" },
t_s_acad: { en:"Academic Passages %1$s", ja:"がくじゅつぶん どっかい %1$s", zh:"学术文章阅读 %1$s", es:"Textos académicos %1$s", fr:"Textes académiques %1$s", de:"Fachtexte lesen %1$s", pt:"Textos acadêmicos %1$s", ru:"Академические тексты %1$s", vi:"Đọc bài học thuật %1$s", th:"อ่านบทความวิชาการ %1$s", in:"Bacaan akademik %1$s" },
t_s_conv: { en:"Real Conversation %1$s", ja:"じっせん かいわ %1$s", zh:"实战会话 %1$s", es:"Conversación real %1$s", fr:"Conversation réelle %1$s", de:"Echte Konversation %1$s", pt:"Conversação real %1$s", ru:"Живой разговор %1$s", vi:"Hội thoại thực chiến %1$s", th:"สนทนาจริง %1$s", in:"Percakapan nyata %1$s" },
t_s_travel: { en:"Travel Phrases Speaking %1$s", ja:"りょこう ひょうげん スピーキング %1$s", zh:"旅行表达口语 %1$s", es:"Frases de viaje %1$s", fr:"Expressions de voyage %1$s", de:"Reisephrasen sprechen %1$s", pt:"Frases de viagem %1$s", ru:"Дорожные фразы %1$s", vi:"Nói mẫu câu du lịch %1$s", th:"พูดสำนวนท่องเที่ยว %1$s", in:"Bicara frasa perjalanan %1$s" },
t_s_build: { en:"Sentence Building %1$s", ja:"ぶんしょう くみたて %1$s", zh:"句子组装 %1$s", es:"Construcción de frases %1$s", fr:"Construction de phrases %1$s", de:"Satzbau %1$s", pt:"Montagem de frases %1$s", ru:"Сборка предложений %1$s", vi:"Ghép câu %1$s", th:"ประกอบประโยค %1$s", in:"Merakit kalimat %1$s" },
t_s_compose: { en:"Writing Practice %1$s", ja:"えいさくぶん れんしゅう %1$s", zh:"英语写作训练 %1$s", es:"Práctica de redacción %1$s", fr:"Entraînement à la rédaction %1$s", de:"Schreibtraining %1$s", pt:"Prática de escrita %1$s", ru:"Практика письма %1$s", vi:"Luyện viết %1$s", th:"ฝึกแต่งประโยค %1$s", in:"Latihan menulis %1$s" },
t_s_acread: { en:"Academic Reading %1$s", ja:"アカデミック どっかい %1$s", zh:"学术阅读 %1$s", es:"Lectura académica %1$s", fr:"Lecture académique %1$s", de:"Akademisches Lesen %1$s", pt:"Leitura acadêmica %1$s", ru:"Академическое чтение %1$s", vi:"Đọc học thuật %1$s", th:"การอ่านเชิงวิชาการ %1$s", in:"Membaca akademik %1$s" },
t_s_lecture: { en:"Lecture Listening %1$s", ja:"こうぎ リスニング %1$s", zh:"讲座听力 %1$s", es:"Escucha de clases %1$s", fr:"Écoute de cours %1$s", de:"Vorlesungs-Hören %1$s", pt:"Escuta de aulas %1$s", ru:"Аудирование лекций %1$s", vi:"Nghe bài giảng %1$s", th:"ฟังบรรยาย %1$s", in:"Menyimak kuliah %1$s" },
t_s_acvocab: { en:"Academic Vocabulary Lab %1$s", ja:"がくじゅつ ごい けんきゅうじょ %1$s", zh:"学术词汇研究所 %1$s", es:"Laboratorio de vocabulario académico %1$s", fr:"Labo de vocabulaire académique %1$s", de:"Fachwortschatz-Labor %1$s", pt:"Laboratório de vocabulário acadêmico %1$s", ru:"Лаборатория академической лексики %1$s", vi:"Phòng thí nghiệm từ vựng học thuật %1$s", th:"แล็บคำศัพท์วิชาการ %1$s", in:"Lab kosakata akademik %1$s" },
t_s_p5: { en:"Part %1$s Fill-in-the-blank %2$s", ja:"Part %1$s あなうめ %2$s", zh:"Part %1$s 填空 %2$s", es:"Part %1$s Rellenar huecos %2$s", fr:"Part %1$s Texte à trous %2$s", de:"Part %1$s Lückentext %2$s", pt:"Part %1$s Preencher lacunas %2$s", ru:"Part %1$s Заполни пропуск %2$s", vi:"Part %1$s Điền chỗ trống %2$s", th:"Part %1$s เติมคำในช่องว่าง %2$s", in:"Part %1$s Isi bagian kosong %2$s" },
t_s_p7: { en:"Part %1$s Reading %2$s", ja:"Part %1$s どっかい %2$s", zh:"Part %1$s 阅读 %2$s", es:"Part %1$s Lectura %2$s", fr:"Part %1$s Lecture %2$s", de:"Part %1$s Lesen %2$s", pt:"Part %1$s Leitura %2$s", ru:"Part %1$s Чтение %2$s", vi:"Part %1$s Đọc hiểu %2$s", th:"Part %1$s การอ่าน %2$s", in:"Part %1$s Membaca %2$s" },
t_s_lc: { en:"LC Short Dialogs %1$s", ja:"LC みじかい かいわ %1$s", zh:"LC 短对话 %1$s", es:"LC Diálogos cortos %1$s", fr:"LC Dialogues courts %1$s", de:"LC Kurzdialoge %1$s", pt:"LC Diálogos curtos %1$s", ru:"LC Короткие диалоги %1$s", vi:"LC Hội thoại ngắn %1$s", th:"LC บทสนทนาสั้น %1$s", in:"LC Dialog pendek %1$s" },
t_s_bizvocab: { en:"Business Vocabulary Drill %1$s", ja:"ビジネス ごい とっくん %1$s", zh:"商务词汇特训 %1$s", es:"Vocabulario de negocios %1$s", fr:"Vocabulaire des affaires %1$s", de:"Business-Wortschatz-Drill %1$s", pt:"Vocabulário de negócios %1$s", ru:"Деловая лексика: тренировка %1$s", vi:"Luyện từ vựng thương mại %1$s", th:"ติวศัพท์ธุรกิจ %1$s", in:"Latihan kosakata bisnis %1$s" },
t_s_shortdialog: { en:"Short Dialog Listening", ja:"みじかい かいわを きく", zh:"听短对话", es:"Escucha de diálogos cortos", fr:"Écoute de dialogues courts", de:"Kurzdialoge hören", pt:"Escuta de diálogos curtos", ru:"Слушаем короткие диалоги", vi:"Nghe hội thoại ngắn", th:"ฟังบทสนทนาสั้น", in:"Menyimak dialog pendek" },

};
