/**
 * 삐약영어 전용 문제 화면 문자열 (수학과 겹치지 않는 것들).
 * 겹치는 것(칭찬·격려·정답: 등)은 ui_lesson.js 를 그대로 재사용한다.
 */
module.exports = {

// ---------- 문제 종류 라벨 ----------
kind_listen: { ko:"🎧 듣기", en:"🎧 Listening", ja:"🎧 リスニング", zh:"🎧 听力", es:"🎧 Escuchar", fr:"🎧 Écoute", de:"🎧 Hören", pt:"🎧 Escuta", ru:"🎧 Аудирование", vi:"🎧 Nghe", th:"🎧 การฟัง", in:"🎧 Menyimak" },
kind_dialog: { ko:"🎧 대화 듣기", en:"🎧 Dialog", ja:"🎧 かいわを きく", zh:"🎧 听对话", es:"🎧 Diálogo", fr:"🎧 Dialogue", de:"🎧 Dialog", pt:"🎧 Diálogo", ru:"🎧 Диалог", vi:"🎧 Hội thoại", th:"🎧 ฟังบทสนทนา", in:"🎧 Dialog" },
kind_dictation: { ko:"✍️ 받아쓰기", en:"✍️ Dictation", ja:"✍️ かきとり", zh:"✍️ 听写", es:"✍️ Dictado", fr:"✍️ Dictée", de:"✍️ Diktat", pt:"✍️ Ditado", ru:"✍️ Диктант", vi:"✍️ Chính tả", th:"✍️ เขียนตามคำบอก", in:"✍️ Dikte" },
kind_compose: { ko:"✍️ 영작", en:"✍️ Writing", ja:"✍️ えいさくぶん", zh:"✍️ 英语写作", es:"✍️ Redacción", fr:"✍️ Rédaction", de:"✍️ Schreiben", pt:"✍️ Escrita", ru:"✍️ Письмо", vi:"✍️ Viết câu", th:"✍️ แต่งประโยค", in:"✍️ Menulis" },
kind_reading: { ko:"📖 독해", en:"📖 Reading", ja:"📖 どっかい", zh:"📖 阅读", es:"📖 Lectura", fr:"📖 Lecture", de:"📖 Lesen", pt:"📖 Leitura", ru:"📖 Чтение", vi:"📖 Đọc hiểu", th:"📖 การอ่าน", in:"📖 Membaca" },
kind_pic: { ko:"🎨 그림 문제", en:"🎨 Picture question", ja:"🎨 えの もんだい", zh:"🎨 图画题", es:"🎨 Pregunta con dibujo", fr:"🎨 Question illustrée", de:"🎨 Bildaufgabe", pt:"🎨 Questão com figura", ru:"🎨 Задание с картинкой", vi:"🎨 Câu hỏi hình ảnh", th:"🎨 โจทย์รูปภาพ", in:"🎨 Soal bergambar" },
kind_choose: { ko:"🔤 고르기", en:"🔤 Choose", ja:"🔤 えらぶ", zh:"🔤 选择", es:"🔤 Elegir", fr:"🔤 Choisir", de:"🔤 Auswählen", pt:"🔤 Escolher", ru:"🔤 Выбор", vi:"🔤 Chọn", th:"🔤 เลือกคำตอบ", in:"🔤 Memilih" },

// ---------- 받아쓰기·영작 ----------
dictation_prompt: { ko:"들리는 대로 영어로 써 보세요", en:"Type what you hear in English", ja:"きこえた とおりに えいごで かこう", zh:"把听到的用英语写下来", es:"Escribe en inglés lo que oigas", fr:"Écris en anglais ce que tu entends", de:"Schreib auf Englisch, was du hörst", pt:"Escreva em inglês o que ouvir", ru:"Напиши по-английски то, что услышал", vi:"Gõ lại bằng tiếng Anh những gì bạn nghe", th:"พิมพ์สิ่งที่ได้ยินเป็นภาษาอังกฤษ", in:"Ketik yang kamu dengar dalam bahasa Inggris" },
hint_prefix: { ko:"힌트: %1$s", en:"Hint: %1$s", ja:"ヒント: %1$s", zh:"提示: %1$s", es:"Pista: %1$s", fr:"Indice : %1$s", de:"Tipp: %1$s", pt:"Dica: %1$s", ru:"Подсказка: %1$s", vi:"Gợi ý: %1$s", th:"คำใบ้: %1$s", in:"Petunjuk: %1$s" },
typo_ok: { ko:"오타가 조금 있었지만 인정! ✔ %1$s", en:"A small typo, but we'll take it! ✔ %1$s", ja:"すこし タイプミスが あったけど OK! ✔ %1$s", zh:"有点小笔误，但算你对! ✔ %1$s", es:"Un pequeño error de tecleo, ¡pero vale! ✔ %1$s", fr:"Petite faute de frappe, mais c'est bon ! ✔ %1$s", de:"Kleiner Tippfehler, zählt trotzdem! ✔ %1$s", pt:"Um errinho de digitação, mas vale! ✔ %1$s", ru:"Небольшая опечатка, но засчитано! ✔ %1$s", vi:"Có lỗi gõ nhỏ nhưng vẫn tính! ✔ %1$s", th:"พิมพ์ผิดนิดหน่อยแต่ให้ผ่าน! ✔ %1$s", in:"Ada salah ketik sedikit, tapi diterima! ✔ %1$s" },

// ---------- 듣기 ----------
heard_was: { ko:"%1$s  (들려준 말: %2$s)", en:"%1$s  (you heard: %2$s)", ja:"%1$s  (きこえた ことば: %2$s)", zh:"%1$s  (播放的是: %2$s)", es:"%1$s  (escuchaste: %2$s)", fr:"%1$s  (tu as entendu : %2$s)", de:"%1$s  (du hörtest: %2$s)", pt:"%1$s  (você ouviu: %2$s)", ru:"%1$s  (прозвучало: %2$s)", vi:"%1$s  (bạn đã nghe: %2$s)", th:"%1$s  (ที่ได้ยินคือ: %2$s)", in:"%1$s  (yang kamu dengar: %2$s)" },
skip_btn: { ko:"잘 모르겠어요 (건너뛰기)", en:"Not sure (skip)", ja:"よく わからない (スキップ)", zh:"不太会 (跳过)", es:"No lo sé (saltar)", fr:"Je ne sais pas (passer)", de:"Weiß nicht (überspringen)", pt:"Não sei (pular)", ru:"Не знаю (пропустить)", vi:"Chưa chắc (bỏ qua)", th:"ไม่แน่ใจ (ข้าม)", in:"Tidak yakin (lewati)" },

// ---------- 말하기 (발음 인식) ----------
speak_listening: { ko:"🎙 듣고 있어요… 문장을 읽어 주세요!", en:"🎙 Listening… read the sentence!", ja:"🎙 きいてるよ… ぶんしょうを よんでね!", zh:"🎙 正在听… 请读出句子!", es:"🎙 Escuchando… ¡lee la frase!", fr:"🎙 J'écoute… lis la phrase !", de:"🎙 Ich höre zu… lies den Satz!", pt:"🎙 Ouvindo… leia a frase!", ru:"🎙 Слушаю… прочитай предложение!", vi:"🎙 Đang nghe… hãy đọc câu nhé!", th:"🎙 กำลังฟัง… อ่านประโยคเลย!", in:"🎙 Mendengarkan… bacalah kalimatnya!" },
speak_heard: { ko:"들린 말: \"%1$s\" (유사도 %2$d%%)", en:"Heard: \"%1$s\" (match %2$d%%)", ja:"きこえた ことば: \"%1$s\" (にてるど %2$d%%)", zh:"听到的是: \"%1$s\" (相似度 %2$d%%)", es:"Se oyó: \"%1$s\" (parecido %2$d%%)", fr:"Entendu : \"%1$s\" (ressemblance %2$d%%)", de:"Gehört: \"%1$s\" (Ähnlichkeit %2$d%%)", pt:"Ouvi: \"%1$s\" (semelhança %2$d%%)", ru:"Услышано: \"%1$s\" (сходство %2$d%%)", vi:"Nghe được: \"%1$s\" (giống %2$d%%)", th:"ที่ได้ยิน: \"%1$s\" (ใกล้เคียง %2$d%%)", in:"Terdengar: \"%1$s\" (kemiripan %2$d%%)" },
speak_success: { ko:"발음 인식 성공! 유사도 %1$d%%", en:"Great pronunciation! Match %1$d%%", ja:"はつおん にんしき せいこう! にてるど %1$d%%", zh:"发音识别成功! 相似度 %1$d%%", es:"¡Buena pronunciación! Parecido %1$d%%", fr:"Bonne prononciation ! Ressemblance %1$d%%", de:"Super Aussprache! Ähnlichkeit %1$d%%", pt:"Ótima pronúncia! Semelhança %1$d%%", ru:"Отличное произношение! Сходство %1$d%%", vi:"Phát âm tốt! Giống %1$d%%", th:"ออกเสียงเยี่ยม! ใกล้เคียง %1$d%%", in:"Pelafalan bagus! Kemiripan %1$d%%" },
speak_retry: { ko:"조금 달라요! 다시 시도해 보세요 🐥", en:"Not quite! Try again 🐥", ja:"ちょっと ちがうよ! もういちど やってみよう 🐥", zh:"有点不一样! 再试一次吧 🐥", es:"¡Casi! Inténtalo otra vez 🐥", fr:"Pas tout à fait ! Réessaie 🐥", de:"Fast! Versuch es noch mal 🐥", pt:"Quase! Tente de novo 🐥", ru:"Немного не так! Попробуй ещё раз 🐥", vi:"Hơi khác một chút! Thử lại nhé 🐥", th:"ยังไม่ตรงนัก! ลองอีกครั้ง 🐥", in:"Sedikit beda! Coba lagi ya 🐥" },
speak_not_heard: { ko:"잘 안 들렸어요. 다시 눌러서 또박또박 읽어 주세요!", en:"Couldn't hear you. Tap again and speak clearly!", ja:"よく きこえなかったよ。もういちど おして はっきり よんでね!", zh:"没听清楚。再按一次，清楚地读出来!", es:"No se oyó bien. ¡Pulsa otra vez y habla claro!", fr:"Je n'ai pas bien entendu. Appuie encore et parle bien fort !", de:"Ich konnte dich nicht hören. Tippe noch mal und sprich deutlich!", pt:"Não deu para ouvir. Toque de novo e fale com clareza!", ru:"Плохо слышно. Нажми ещё раз и говори чётко!", vi:"Nghe không rõ. Bấm lại và đọc thật rõ nhé!", th:"ฟังไม่ชัด กดอีกครั้งแล้วอ่านชัด ๆ นะ!", in:"Kurang terdengar. Tekan lagi dan ucapkan dengan jelas!" },
speak_unavailable: { ko:"이 기기에서 음성인식을 쓸 수 없어요.", en:"Speech recognition isn't available on this device.", ja:"この きき では おんせいにんしきが つかえないよ。", zh:"此设备无法使用语音识别。", es:"El reconocimiento de voz no está disponible en este dispositivo.", fr:"La reconnaissance vocale n'est pas disponible sur cet appareil.", de:"Spracherkennung ist auf diesem Gerät nicht verfügbar.", pt:"O reconhecimento de voz não está disponível neste aparelho.", ru:"Распознавание речи недоступно на этом устройстве.", vi:"Thiết bị này không dùng được nhận dạng giọng nói.", th:"อุปกรณ์นี้ใช้การรู้จำเสียงพูดไม่ได้", in:"Pengenalan suara tidak tersedia di perangkat ini." },
speak_error: { ko:"음성인식 오류(%1$d). 다시 시도해 주세요.", en:"Speech recognition error (%1$d). Please try again.", ja:"おんせいにんしき エラー(%1$d)。もういちど ためしてね。", zh:"语音识别出错(%1$d)。请再试一次。", es:"Error de reconocimiento de voz (%1$d). Inténtalo de nuevo.", fr:"Erreur de reconnaissance vocale (%1$d). Réessaie.", de:"Spracherkennungsfehler (%1$d). Bitte noch mal versuchen.", pt:"Erro no reconhecimento de voz (%1$d). Tente de novo.", ru:"Ошибка распознавания речи (%1$d). Попробуй ещё раз.", vi:"Lỗi nhận dạng giọng nói (%1$d). Hãy thử lại.", th:"การรู้จำเสียงผิดพลาด (%1$d) ลองใหม่อีกครั้ง", in:"Kesalahan pengenalan suara (%1$d). Silakan coba lagi." },
speak_giveup: { ko:"괜찮아요! 다음에 말해 봐요. 정답 문장: %1$s", en:"That's okay! Try saying it next time. The sentence was: %1$s", ja:"だいじょうぶ! つぎに いってみよう。せいかいの ぶんしょう: %1$s", zh:"没关系! 下次再说说看。正确句子: %1$s", es:"¡No pasa nada! Inténtalo la próxima vez. La frase era: %1$s", fr:"Ce n'est pas grave ! Essaie la prochaine fois. La phrase était : %1$s", de:"Kein Problem! Versuch es nächstes Mal. Der Satz war: %1$s", pt:"Tudo bem! Tente falar na próxima. A frase era: %1$s", ru:"Ничего страшного! Скажешь в следующий раз. Предложение: %1$s", vi:"Không sao! Lần sau nói thử nhé. Câu đúng là: %1$s", th:"ไม่เป็นไร! ไว้พูดครั้งหน้า ประโยคที่ถูกคือ: %1$s", in:"Tidak apa-apa! Coba ucapkan lain kali. Kalimatnya: %1$s" },

// ---------- 짝 맞추기 ----------
match_hint: { ko:"🔗 짝이 맞는 것끼리 손가락으로 이어요", en:"🔗 Draw a line between matching pairs", ja:"🔗 あう ペアを ゆびで つなごう", zh:"🔗 用手指把配对的连起来", es:"🔗 Une con el dedo las parejas que coinciden", fr:"🔗 Relie avec le doigt les paires qui vont ensemble", de:"🔗 Verbinde die passenden Paare mit dem Finger", pt:"🔗 Ligue com o dedo os pares que combinam", ru:"🔗 Соедини пальцем подходящие пары", vi:"🔗 Dùng ngón tay nối các cặp khớp nhau", th:"🔗 ใช้นิ้วลากเส้นจับคู่ที่เข้ากัน", in:"🔗 Hubungkan pasangan yang cocok dengan jarimu" },
match_mistakes: { ko:"%1$d번 헷갈렸지만 다 이었어요!", en:"Mixed up %1$d times, but you matched them all!", ja:"%1$d かい まちがえたけど ぜんぶ つなげたよ!", zh:"弄混了 %1$d 次，但全都连对了!", es:"Te confundiste %1$d veces, ¡pero uniste todo!", fr:"Tu t'es trompé %1$d fois, mais tout est relié !", de:"%1$d Mal verwechselt, aber alles verbunden!", pt:"Confundiu %1$d vezes, mas ligou tudo!", ru:"Запутался %1$d раз, но всё соединил!", vi:"Nhầm %1$d lần nhưng đã nối hết!", th:"สับสน %1$d ครั้ง แต่จับคู่ครบหมดแล้ว!", in:"Keliru %1$d kali, tapi semua berhasil dihubungkan!" },

// ---------- 대화 듣기 대본 ----------
dialog_script: { ko:"%1$s\n\n대본:\n%2$s", en:"%1$s\n\nScript:\n%2$s", ja:"%1$s\n\nスクリプト:\n%2$s", zh:"%1$s\n\n对话原文:\n%2$s", es:"%1$s\n\nGuion:\n%2$s", fr:"%1$s\n\nScript :\n%2$s", de:"%1$s\n\nSkript:\n%2$s", pt:"%1$s\n\nRoteiro:\n%2$s", ru:"%1$s\n\nТекст:\n%2$s", vi:"%1$s\n\nLời thoại:\n%2$s", th:"%1$s\n\nบทพูด:\n%2$s", in:"%1$s\n\nNaskah:\n%2$s" },

// ---------- 그만두기 ----------
quit_ask: { ko:"레슨을 그만둘까요?\n진행 상황은 저장되지 않아요", en:"Quit this lesson?\nYour progress won't be saved", ja:"レッスンを やめる?\nすすみぐあいは ほぞんされないよ", zh:"要退出这节课吗?\n进度不会被保存", es:"¿Salir de la lección?\nTu progreso no se guardará", fr:"Quitter la leçon ?\nTa progression ne sera pas enregistrée", de:"Lektion beenden?\nDein Fortschritt wird nicht gespeichert", pt:"Sair da lição?\nSeu progresso não será salvo", ru:"Выйти из урока?\nПрогресс не сохранится", vi:"Thoát bài học?\nTiến độ sẽ không được lưu", th:"ออกจากบทเรียนไหม?\nความคืบหน้าจะไม่ถูกบันทึก", in:"Keluar dari pelajaran?\nProgresmu tidak akan disimpan" },
quit_yes: { ko:"그만두기", en:"Quit", ja:"やめる", zh:"退出", es:"Salir", fr:"Quitter", de:"Beenden", pt:"Sair", ru:"Выйти", vi:"Thoát", th:"ออก", in:"Keluar" },
quit_no: { ko:"계속하기", en:"Keep going", ja:"つづける", zh:"继续", es:"Seguir", fr:"Continuer", de:"Weitermachen", pt:"Continuar", ru:"Продолжить", vi:"Tiếp tục", th:"เรียนต่อ", in:"Lanjutkan" },

};
