/**
 * 홈·통계 화면 문자열 — 자동 생성: node tools/i18n/make_ui_home.js
 * 수학 앱과 원문이 같은 키는 수학 원장에서 베껴 온다 (직접 고치지 말 것).
 */
module.exports = {

// ---------- 수학 앱에서 베껴 온 키 ----------
home_greeting: { ko:"오늘도 삐약삐약 공부해요!", en:"Let's study together today!", ja:"きょうもいっしょにべんきょう！", zh:"今天也一起学习吧！", es:"¡Estudiemos juntos hoy!", fr:"Étudions ensemble aujourd'hui !", de:"Lass uns heute zusammen lernen!", pt:"Vamos estudar juntos hoje!", ru:"Позанимаемся сегодня вместе!", vi:"Hôm nay cùng học nhé!", th:"วันนี้มาเรียนด้วยกันนะ!", in:"Ayo belajar bersama hari ini!" },
home_no_review: { ko:"복습할 오답이 없어요! 삐약 🐥", en:"No mistakes to review! 🐥", ja:"ふくしゅうするもんだいはありません！🐥", zh:"没有需要复习的错题！🐥", es:"¡No hay errores que repasar! 🐥", fr:"Aucune erreur à réviser ! 🐥", de:"Keine Fehler zum Wiederholen! 🐥", pt:"Nada para rever! 🐥", ru:"Нет ошибок для повторения! 🐥", vi:"Không có lỗi nào để ôn! 🐥", th:"ไม่มีข้อผิดที่ต้องทบทวน! 🐥", in:"Tidak ada kesalahan untuk diulang! 🐥" },
goal_light: { ko:"가볍게 (레슨 1개쯤)", en:"Light (about 1 lesson)", ja:"かるく (レッスン 1こくらい)", zh:"轻松 (约1课)", es:"Suave (1 lección)", fr:"Léger (environ 1 leçon)", de:"Locker (etwa 1 Lektion)", pt:"Leve (cerca de 1 lição)", ru:"Легко (около 1 урока)", vi:"Nhẹ nhàng (khoảng 1 bài)", th:"เบา ๆ (ราว 1 บท)", in:"Ringan (sekitar 1 pelajaran)" },
goal_normal: { ko:"보통 (레슨 2~3개)", en:"Normal (2–3 lessons)", ja:"ふつう (レッスン 2〜3こ)", zh:"普通 (2~3课)", es:"Normal (2-3 lecciones)", fr:"Normal (2 à 3 leçons)", de:"Normal (2–3 Lektionen)", pt:"Normal (2 a 3 lições)", ru:"Обычно (2–3 урока)", vi:"Vừa phải (2–3 bài)", th:"ปานกลาง (2–3 บท)", in:"Sedang (2–3 pelajaran)" },
goal_hard: { ko:"열심히 (레슨 5개쯤)", en:"Hard (about 5 lessons)", ja:"がんばる (レッスン 5こくらい)", zh:"努力 (约5课)", es:"Intenso (unas 5 lecciones)", fr:"Intense (environ 5 leçons)", de:"Fleißig (etwa 5 Lektionen)", pt:"Puxado (cerca de 5 lições)", ru:"Усердно (около 5 уроков)", vi:"Chăm chỉ (khoảng 5 bài)", th:"ขยัน (ราว 5 บท)", in:"Rajin (sekitar 5 pelajaran)" },
goal_beast: { ko:"빡세게 (레슨 10개쯤)", en:"Beast mode (about 10 lessons)", ja:"ハード (レッスン 10こくらい)", zh:"硬核 (约10课)", es:"Modo bestia (unas 10 lecciones)", fr:"Mode bête (environ 10 leçons)", de:"Vollgas (etwa 10 Lektionen)", pt:"Modo fera (cerca de 10 lições)", ru:"На максимум (около 10 уроков)", vi:"Cực chăm (khoảng 10 bài)", th:"โหดสุด (ราว 10 บท)", in:"Mode gaspol (sekitar 10 pelajaran)" },
goal_set_title: { ko:"🎯 오늘의 목표 정하기", en:"🎯 Set today's goal", ja:"🎯 きょうの もくひょうを きめる", zh:"🎯 设定今天的目标", es:"🎯 Fija la meta de hoy", fr:"🎯 Fixe l'objectif du jour", de:"🎯 Tagesziel festlegen", pt:"🎯 Defina a meta de hoje", ru:"🎯 Задай цель на сегодня", vi:"🎯 Đặt mục tiêu hôm nay", th:"🎯 ตั้งเป้าหมายวันนี้", in:"🎯 Tetapkan target hari ini" },
cancel: { ko:"취소", en:"Cancel", ja:"キャンセル", zh:"取消", es:"Cancelar", fr:"Annuler", de:"Abbrechen", pt:"Cancelar", ru:"Отмена", vi:"Hủy", th:"ยกเลิก", in:"Batal" },
home_wrong_count: { ko:"오답 %d", en:"Review %d", ja:"まちがい %d", zh:"错题 %d", es:"Repasar %d", fr:"Réviser %d", de:"Fehler %d", pt:"Rever %d", ru:"Ошибки %d", vi:"Ôn %d", th:"ทบทวน %d", in:"Ulangi %d" },
home_overall_lv: { ko:"종합 실력 Lv.%s", en:"Overall Lv.%s", ja:"そうごう Lv.%s", zh:"综合水平 Lv.%s", es:"Nivel global Lv.%s", fr:"Niveau global Lv.%s", de:"Gesamt Lv.%s", pt:"Nível geral Lv.%s", ru:"Общий Ур.%s", vi:"Tổng thể Lv.%s", th:"ระดับรวม Lv.%s", in:"Level total Lv.%s" },
rank_next: { ko:"  →  다음 칭호 %1$s %2$s", en:"  →  Next title %1$s %2$s", ja:"  →  つぎの しょうごう %1$s %2$s", zh:"  →  下一个称号 %1$s %2$s", es:"  →  Siguiente título %1$s %2$s", fr:"  →  Titre suivant %1$s %2$s", de:"  →  Nächster Titel %1$s %2$s", pt:"  →  Próximo título %1$s %2$s", ru:"  →  Следующее звание %1$s %2$s", vi:"  →  Danh hiệu tiếp theo %1$s %2$s", th:"  →  ฉายาถัดไป %1$s %2$s", in:"  →  Gelar berikutnya %1$s %2$s" },
rank_next_short: { ko:"  (→ %1$s Lv.%2$.1f)", en:"  (→ %1$s Lv.%2$.1f)", ja:"  (→ %1$s Lv.%2$.1f)", zh:"  (→ %1$s Lv.%2$.1f)", es:"  (→ %1$s Nv.%2$.1f)", fr:"  (→ %1$s niv.%2$.1f)", de:"  (→ %1$s Lv.%2$.1f)", pt:"  (→ %1$s Nv.%2$.1f)", ru:"  (→ %1$s ур.%2$.1f)", vi:"  (→ %1$s cấp %2$.1f)", th:"  (→ %1$s Lv.%2$.1f)", in:"  (→ %1$s Lv.%2$.1f)" },
rank_top: { ko:"  (최고 칭호!)", en:"  (top title!)", ja:"  (さいこうの しょうごう!)", zh:"  (最高称号!)", es:"  (¡título máximo!)", fr:"  (titre suprême !)", de:"  (höchster Titel!)", pt:"  (título máximo!)", ru:"  (высшее звание!)", vi:"  (danh hiệu cao nhất!)", th:"  (ฉายาสูงสุด!)", in:"  (gelar tertinggi!)" },
home_daily_goal: { ko:"오늘의 목표  %1$d / %2$d XP", en:"Today's goal  %1$d / %2$d XP", ja:"きょうのもくひょう  %1$d / %2$d XP", zh:"今日目标  %1$d / %2$d XP", es:"Meta de hoy  %1$d / %2$d XP", fr:"Objectif du jour  %1$d / %2$d XP", de:"Tagesziel  %1$d / %2$d XP", pt:"Meta de hoje  %1$d / %2$d XP", ru:"Цель дня  %1$d / %2$d XP", vi:"Mục tiêu hôm nay  %1$d / %2$d XP", th:"เป้าหมายวันนี้  %1$d / %2$d XP", in:"Target hari ini  %1$d / %2$d XP" },
home_goal_done: { ko:"   ✅ 달성!", en:"  ✅ Done!", ja:"  ✅ たっせい！", zh:"  ✅ 达成！", es:"  ✅ ¡Logrado!", fr:"  ✅ Atteint !", de:"  ✅ Geschafft!", pt:"  ✅ Concluído!", ru:"  ✅ Готово!", vi:"  ✅ Đạt rồi!", th:"  ✅ สำเร็จ!", in:"  ✅ Tercapai!" },
weak_area: { ko:"약한 영역: %1$s %2$s", en:"Weakest area: %1$s %2$s", ja:"よわい りょういき: %1$s %2$s", zh:"薄弱领域: %1$s %2$s", es:"Área más floja: %1$s %2$s", fr:"Point faible : %1$s %2$s", de:"Schwächster Bereich: %1$s %2$s", pt:"Área mais fraca: %1$s %2$s", ru:"Слабая область: %1$s %2$s", vi:"Điểm yếu: %1$s %2$s", th:"จุดอ่อน: %1$s %2$s", in:"Bidang terlemah: %1$s %2$s" },
not_started: { ko:"  시작 전", en:"  Not started", ja:"  まだ", zh:"  未开始", es:"  Sin empezar", fr:"  Pas commencé", de:"  Noch nicht begonnen", pt:"  Não iniciado", ru:"  Не начато", vi:"  Chưa bắt đầu", th:"  ยังไม่เริ่ม", in:"  Belum dimulai" },
home_placement_math: { ko:"레벨테스트로 내 학년 찾기!\n25문제로 딱 맞는 단계를 정해줘요", en:"Find your grade with a placement test!\n25 questions pick the right level for you", ja:"レベルテストで じぶんの がくねんを さがそう!\n25もんで ぴったりの だんかいを きめるよ", zh:"用分级测试找到适合的年级!\n25道题为你定好合适的阶段", es:"¡Encuentra tu curso con la prueba de nivel!\n25 preguntas eligen el nivel exacto", fr:"Trouve ton niveau avec le test !\n25 questions choisissent l'étape qui te convient", de:"Finde deine Klassenstufe mit dem Einstufungstest!\n25 Fragen bestimmen die passende Stufe", pt:"Descubra seu ano com o teste de nível!\n25 questões escolhem o estágio certo", ru:"Найди свой класс с помощью теста!\n25 вопросов подберут подходящий уровень", vi:"Tìm đúng lớp bằng bài kiểm tra trình độ!\n25 câu sẽ chọn giai đoạn phù hợp", th:"หาระดับชั้นของคุณด้วยแบบทดสอบ!\n25 ข้อจะเลือกขั้นที่เหมาะสมให้", in:"Temukan tingkatmu lewat tes penempatan!\n25 soal memilih tahap yang pas" },
stats_level_big: { ko:"⭐ Lv.%1$d", en:"⭐ Lv.%1$d", ja:"⭐ Lv.%1$d", zh:"⭐ Lv.%1$d", es:"⭐ Nv.%1$d", fr:"⭐ Niv.%1$d", de:"⭐ Lv.%1$d", pt:"⭐ Nv.%1$d", ru:"⭐ Ур.%1$d", vi:"⭐ Cấp %1$d", th:"⭐ Lv.%1$d", in:"⭐ Lv.%1$d" },
stats_xp_detail: { ko:"누적 %1$d XP · 다음 레벨까지 %2$d XP", en:"%1$d XP total · %2$d XP to next level", ja:"るいけい %1$d XP · つぎの レベルまで %2$d XP", zh:"累计 %1$d XP · 距下一级 %2$d XP", es:"%1$d XP en total · %2$d XP al siguiente nivel", fr:"%1$d XP au total · %2$d XP avant le niveau suivant", de:"%1$d XP gesamt · %2$d XP bis zum nächsten Level", pt:"%1$d XP no total · %2$d XP para o próximo nível", ru:"Всего %1$d XP · до следующего уровня %2$d XP", vi:"Tổng %1$d XP · còn %2$d XP lên cấp", th:"รวม %1$d XP · อีก %2$d XP ถึงระดับถัดไป", in:"Total %1$d XP · %2$d XP lagi naik level" },
stats_streak_info: { ko:"현재 %1$d일 연속 · 최고 %2$d일", en:"%1$d-day streak · best %2$d days", ja:"いま %1$d日 れんぞく · さいこう %2$d日", zh:"当前连续 %1$d 天 · 最长 %2$d 天", es:"Racha de %1$d días · mejor %2$d días", fr:"Série de %1$d jours · record %2$d jours", de:"%1$d Tage in Folge · Rekord %2$d Tage", pt:"Sequência de %1$d dias · recorde %2$d dias", ru:"Серия %1$d дней · рекорд %2$d дней", vi:"Chuỗi %1$d ngày · kỷ lục %2$d ngày", th:"ต่อเนื่อง %1$d วัน · สูงสุด %2$d วัน", in:"Beruntun %1$d hari · terbaik %2$d hari" },
stats_counters: { ko:"📚 완료한 레슨  %1$d개\n💯 퍼펙트 레슨  %2$d개\n💊 클리어한 오답  %3$d개\n🗓 공부한 날  %4$d일", en:"📚 Lessons finished  %1$d\n💯 Perfect lessons  %2$d\n💊 Mistakes cleared  %3$d\n🗓 Days studied  %4$d", ja:"📚 おわった レッスン  %1$d\n💯 パーフェクト  %2$d\n💊 クリアした まちがい  %3$d\n🗓 べんきょうした日  %4$d", zh:"📚 完成的课程  %1$d\n💯 满分课程  %2$d\n💊 攻克的错题  %3$d\n🗓 学习天数  %4$d", es:"📚 Lecciones completadas  %1$d\n💯 Lecciones perfectas  %2$d\n💊 Errores superados  %3$d\n🗓 Días estudiados  %4$d", fr:"📚 Leçons terminées  %1$d\n💯 Leçons parfaites  %2$d\n💊 Erreurs corrigées  %3$d\n🗓 Jours étudiés  %4$d", de:"📚 Abgeschlossene Lektionen  %1$d\n💯 Perfekte Lektionen  %2$d\n💊 Erledigte Fehler  %3$d\n🗓 Lerntage  %4$d", pt:"📚 Lições concluídas  %1$d\n💯 Lições perfeitas  %2$d\n💊 Erros superados  %3$d\n🗓 Dias estudados  %4$d", ru:"📚 Пройдено уроков  %1$d\n💯 Идеальных уроков  %2$d\n💊 Закрыто ошибок  %3$d\n🗓 Дней занятий  %4$d", vi:"📚 Bài học hoàn thành  %1$d\n💯 Bài hoàn hảo  %2$d\n💊 Câu sai đã xử lý  %3$d\n🗓 Số ngày học  %4$d", th:"📚 บทที่เรียนจบ  %1$d\n💯 บทที่ได้เต็ม  %2$d\n💊 ข้อผิดที่แก้แล้ว  %3$d\n🗓 วันที่เรียน  %4$d", in:"📚 Pelajaran selesai  %1$d\n💯 Pelajaran sempurna  %2$d\n💊 Kesalahan tuntas  %3$d\n🗓 Hari belajar  %4$d" },
stats_none_yet: { ko:"아직 풀어본 문제가 없어요", en:"No questions solved yet", ja:"まだ といた もんだいが ないよ", zh:"还没做过题", es:"Aún no has resuelto preguntas", fr:"Aucune question résolue pour l'instant", de:"Noch keine Aufgaben gelöst", pt:"Nenhuma questão resolvida ainda", ru:"Пока нет решённых задач", vi:"Chưa giải câu nào", th:"ยังไม่ได้ทำโจทย์", in:"Belum ada soal dikerjakan" },
stats_skill_line: { ko:"정답 %1$d / 시도 %2$d  ·  정답률 %3$d%%", en:"%1$d correct / %2$d tries  ·  %3$d%% accuracy", ja:"せいかい %1$d / ちょうせん %2$d  ·  せいかいりつ %3$d%%", zh:"答对 %1$d / 尝试 %2$d  ·  正确率 %3$d%%", es:"%1$d aciertos / %2$d intentos  ·  %3$d%% de acierto", fr:"%1$d bonnes / %2$d essais  ·  %3$d%% de réussite", de:"%1$d richtig / %2$d Versuche  ·  %3$d%% Trefferquote", pt:"%1$d certas / %2$d tentativas  ·  %3$d%% de acerto", ru:"%1$d верно / %2$d попыток  ·  точность %3$d%%", vi:"%1$d đúng / %2$d lần  ·  chính xác %3$d%%", th:"ถูก %1$d / ลอง %2$d  ·  ความแม่นยำ %3$d%%", in:"%1$d benar / %2$d percobaan  ·  akurasi %3$d%%" },
stats_next_level: { ko:"  ·  다음 레벨까지 %1$d문제", en:"  ·  %1$d more to level up", ja:"  ·  つぎの レベルまで %1$d もん", zh:"  ·  距升级还差 %1$d 题", es:"  ·  %1$d más para subir de nivel", fr:"  ·  %1$d de plus pour monter", de:"  ·  noch %1$d bis zum Aufstieg", pt:"  ·  mais %1$d para subir de nível", ru:"  ·  ещё %1$d до уровня", vi:"  ·  còn %1$d câu để lên cấp", th:"  ·  อีก %1$d ข้อจะเลื่อนระดับ", in:"  ·  %1$d lagi untuk naik level" },
stats_max_level: { ko:"  ·  최고 레벨!", en:"  ·  Max level!", ja:"  ·  さいこう レベル!", zh:"  ·  已达最高等级!", es:"  ·  ¡Nivel máximo!", fr:"  ·  Niveau max !", de:"  ·  Höchstlevel!", pt:"  ·  Nível máximo!", ru:"  ·  Максимальный уровень!", vi:"  ·  Cấp tối đa!", th:"  ·  ระดับสูงสุด!", in:"  ·  Level maksimum!" },

// ---------- 홈 인사말 (영어 앱 전용 문구) ----------
home_greeting_2: { ko:"꾸준함이 최고의 재능이에요 🐥", en:"Consistency is the greatest talent 🐥", ja:"つづける ことが さいこうの さいのう 🐥", zh:"坚持就是最好的天赋 🐥", es:"La constancia es el mayor talento 🐥", fr:"La régularité est le plus grand talent 🐥", de:"Dranbleiben ist das größte Talent 🐥", pt:"Constância é o maior talento 🐥", ru:"Постоянство — главный талант 🐥", vi:"Kiên trì là tài năng lớn nhất 🐥", th:"ความสม่ำเสมอคือพรสวรรค์ที่ดีที่สุด 🐥", in:"Konsisten adalah bakat terbaik 🐥" },
home_greeting_3: { ko:"한 문제라도 풀면 오늘은 성공!", en:"Solve even one question and today's a win!", ja:"1もんでも とけたら きょうは せいこう!", zh:"哪怕只做一题，今天也算成功!", es:"¡Con una sola pregunta, hoy ya es un éxito!", fr:"Une seule question résolue et la journée est gagnée !", de:"Schon eine Aufgabe gelöst — heute ist ein Erfolg!", pt:"Resolveu uma questão? O dia já valeu!", ru:"Решил хоть одну задачу — день удался!", vi:"Giải dù một câu thôi, hôm nay đã thành công!", th:"แค่ทำได้ข้อเดียว วันนี้ก็สำเร็จแล้ว!", in:"Kerjakan satu soal saja, hari ini sudah sukses!" },
home_greeting_4: { ko:"삐약! 영어가 무서우면 저를 봐요!", en:"Peep! Scared of English? Look at me!", ja:"ピヨ! えいごが こわいときは わたしを みてね!", zh:"叽叽! 怕英语的话就看看我!", es:"¡Pío! ¿Miedo al inglés? ¡Mírame!", fr:"Cui-cui ! Peur de l'anglais ? Regarde-moi !", de:"Piep! Angst vor Englisch? Schau mich an!", pt:"Piu! Medo de inglês? Olhe para mim!", ru:"Пи-пи! Боишься английского? Смотри на меня!", vi:"Chíp chíp! Sợ tiếng Anh ư? Nhìn tớ này!", th:"จิ๊บ! กลัวภาษาอังกฤษเหรอ มองฉันสิ!", in:"Ciap! Takut bahasa Inggris? Lihat aku!" },
home_greeting_5: { ko:"어제의 나보다 한 단어 더!", en:"One more word than yesterday's me!", ja:"きのうの じぶんより 1たんご おおく!", zh:"比昨天的自己多一个单词!", es:"¡Una palabra más que ayer!", fr:"Un mot de plus qu'hier !", de:"Ein Wort mehr als gestern!", pt:"Uma palavra a mais que ontem!", ru:"На одно слово больше, чем вчера!", vi:"Hơn mình hôm qua một từ!", th:"มากกว่าเมื่อวานอีกหนึ่งคำ!", in:"Satu kata lebih banyak dari kemarin!" },
home_greeting_6: { ko:"여행 가서 써먹을 그날까지 ✈️", en:"Until the day you use it on a trip ✈️", ja:"りょこうで つかえる ひまで ✈️", zh:"直到旅行时用上的那天 ✈️", es:"Hasta el día que lo uses de viaje ✈️", fr:"Jusqu'au jour où tu t'en serviras en voyage ✈️", de:"Bis zu dem Tag, an dem du es auf Reisen brauchst ✈️", pt:"Até o dia de usar numa viagem ✈️", ru:"До того дня, когда пригодится в путешествии ✈️", vi:"Đến ngày dùng được khi đi du lịch ✈️", th:"จนถึงวันที่ได้ใช้ตอนไปเที่ยว ✈️", in:"Sampai hari kamu memakainya saat liburan ✈️" },

// ---------- 레벨테스트 배너 (영어판) ----------
home_placement_en: { ko:"레벨테스트로 내 위치 찾기!\n25문제로 딱 맞는 레벨을 정해줘요", en:"Find your level with a placement test!\n25 questions pick the right level for you", ja:"レベルテストで じぶんの いちを みつけよう!\n25もんで ぴったりの レベルを きめるよ", zh:"用分级测试找到你的位置!\n25道题帮你定好合适的级别", es:"¡Encuentra tu nivel con la prueba!\n25 preguntas eligen el nivel perfecto", fr:"Trouve ton niveau avec le test !\n25 questions choisissent le bon niveau", de:"Finde dein Level mit dem Einstufungstest!\n25 Fragen bestimmen die richtige Stufe", pt:"Descubra seu nível com o teste!\n25 questões definem o nível certo", ru:"Найди свой уровень с тестом!\n25 вопросов подберут подходящий уровень", vi:"Tìm trình độ của bạn bằng bài kiểm tra!\n25 câu chọn đúng cấp độ cho bạn", th:"หาระดับของคุณด้วยแบบทดสอบ!\n25 ข้อช่วยเลือกระดับที่เหมาะสม", in:"Temukan levelmu lewat tes penempatan!\n25 soal menentukan level yang pas" },

// ---------- 홈 단계 카드 5장 ----------
stage_kinder: { ko:"유치원 영어", en:"Preschool English", ja:"ようちえん えいご", zh:"幼儿英语", es:"Inglés preescolar", fr:"Anglais maternelle", de:"Kindergarten-Englisch", pt:"Inglês infantil", ru:"Английский для малышей", vi:"Tiếng Anh mầm non", th:"อังกฤษอนุบาล", in:"Inggris TK" },
stage_kinder_sub: { ko:"알파벳 쓰기 · 놀이터", en:"Alphabet writing · Playground", ja:"アルファベット かき · あそびば", zh:"字母书写 · 游乐场", es:"Escribir el alfabeto · Zona de juegos", fr:"Écriture de l'alphabet · Aire de jeux", de:"Alphabet schreiben · Spielplatz", pt:"Escrever o alfabeto · Parquinho", ru:"Письмо алфавита · Игровая площадка", vi:"Viết bảng chữ cái · Sân chơi", th:"หัดเขียนตัวอักษร · สนามเด็กเล่น", in:"Menulis alfabet · Taman bermain" },
stage_elem: { ko:"초등 영어", en:"Elementary English", ja:"しょうがく えいご", zh:"小学英语", es:"Inglés de primaria", fr:"Anglais primaire", de:"Grundschul-Englisch", pt:"Inglês fundamental", ru:"Английский для начальной школы", vi:"Tiếng Anh tiểu học", th:"อังกฤษประถม", in:"Inggris SD" },
stage_elem_sub: { ko:"초등영어 코스 · 기초 1~6학년", en:"Elementary course · Basics grades 1–6", ja:"しょうがく コース · きそ 1~6ねん", zh:"小学课程 · 基础1~6年级", es:"Curso de primaria · Básico 1º–6º", fr:"Cours primaire · Bases années 1–6", de:"Grundschulkurs · Basis Klasse 1–6", pt:"Curso fundamental · Básico 1º–6º ano", ru:"Курс начальной школы · Базовый 1–6 класс", vi:"Khóa tiểu học · Cơ bản lớp 1–6", th:"คอร์สประถม · พื้นฐาน ป.1–6", in:"Kursus SD · Dasar kelas 1–6" },
stage_middle: { ko:"중등 · 고등 영어", en:"Middle & high school English", ja:"ちゅうがく · こうこう えいご", zh:"初中·高中英语", es:"Inglés de secundaria", fr:"Anglais collège · lycée", de:"Mittel- und Oberstufen-Englisch", pt:"Inglês do ensino médio", ru:"Английский для средней и старшей школы", vi:"Tiếng Anh THCS · THPT", th:"อังกฤษมัธยม", in:"Inggris SMP · SMA" },
stage_middle_sub: { ko:"학년별 기초 · 문법 · 독해", en:"Basics by grade · Grammar · Reading", ja:"がくねんべつ きそ · ぶんぽう · どっかい", zh:"按年级基础 · 语法 · 阅读", es:"Base por curso · Gramática · Lectura", fr:"Bases par niveau · Grammaire · Lecture", de:"Basis je Klasse · Grammatik · Lesen", pt:"Básico por ano · Gramática · Leitura", ru:"База по классам · Грамматика · Чтение", vi:"Cơ bản theo lớp · Ngữ pháp · Đọc hiểu", th:"พื้นฐานตามชั้น · ไวยากรณ์ · การอ่าน", in:"Dasar per kelas · Tata bahasa · Membaca" },
stage_adult: { ko:"성인 · 실전 영어", en:"Adult & practical English", ja:"おとな · じっせん えいご", zh:"成人·实用英语", es:"Inglés adulto y práctico", fr:"Anglais adulte · pratique", de:"Erwachsenen- und Praxis-Englisch", pt:"Inglês adulto e prático", ru:"Английский для взрослых · практика", vi:"Tiếng Anh người lớn · thực chiến", th:"อังกฤษผู้ใหญ่ · ใช้จริง", in:"Inggris dewasa · praktis" },
stage_adult_sub: { ko:"회화 · 토익 · 토플", en:"Conversation · TOEIC · TOEFL", ja:"かいわ · TOEIC · TOEFL", zh:"会话 · 托业 · 托福", es:"Conversación · TOEIC · TOEFL", fr:"Conversation · TOEIC · TOEFL", de:"Konversation · TOEIC · TOEFL", pt:"Conversação · TOEIC · TOEFL", ru:"Разговор · TOEIC · TOEFL", vi:"Hội thoại · TOEIC · TOEFL", th:"สนทนา · TOEIC · TOEFL", in:"Percakapan · TOEIC · TOEFL" },
stage_skills: { ko:"영역별 훈련", en:"Skill-by-skill training", ja:"ぶんやべつ トレーニング", zh:"分领域训练", es:"Entrenamiento por áreas", fr:"Entraînement par compétence", de:"Training nach Bereich", pt:"Treino por área", ru:"Тренировка по областям", vi:"Luyện theo kỹ năng", th:"ฝึกตามทักษะ", in:"Latihan per area" },
stage_skills_sub: { ko:"듣기 · 말하기 · 쓰기 · 문법 · 독해", en:"Listening · Speaking · Writing · Grammar · Reading", ja:"リスニング · スピーキング · ライティング · ぶんぽう · どっかい", zh:"听力 · 口语 · 写作 · 语法 · 阅读", es:"Escucha · Habla · Escritura · Gramática · Lectura", fr:"Écoute · Oral · Écriture · Grammaire · Lecture", de:"Hören · Sprechen · Schreiben · Grammatik · Lesen", pt:"Escuta · Fala · Escrita · Gramática · Leitura", ru:"Аудирование · Говорение · Письмо · Грамматика · Чтение", vi:"Nghe · Nói · Viết · Ngữ pháp · Đọc", th:"ฟัง · พูด · เขียน · ไวยากรณ์ · อ่าน", in:"Menyimak · Berbicara · Menulis · Tata bahasa · Membaca" },

};
