/**
 * 실력 영역·칭호·배지 이름 — 자동 생성: node tools/i18n/make_ui_skills.js
 * 수학 앱과 원문이 같은 키는 수학의 ui_data.js 에서 베껴 온다 (직접 고치지 말 것).
 */
module.exports = {

// ---------- 수학 앱에서 베껴 온 키 ----------
sk_calc: { ko:"계산", en:"Calculation", ja:"けいさん", zh:"计算", es:"Cálculo", fr:"Calcul", de:"Rechnen", pt:"Cálculo", ru:"Вычисления", vi:"Tính toán", th:"การคำนวณ", in:"Berhitung" },
sk_number: { ko:"수 감각", en:"Number sense", ja:"かずのかんかく", zh:"数感", es:"Sentido numérico", fr:"Sens du nombre", de:"Zahlenverständnis", pt:"Senso numérico", ru:"Чувство числа", vi:"Cảm nhận số", th:"ความรู้สึกเชิงจำนวน", in:"Kepekaan bilangan" },
sk_shape: { ko:"도형", en:"Shapes", ja:"ずけい", zh:"图形", es:"Figuras", fr:"Figures", de:"Formen", pt:"Figuras", ru:"Фигуры", vi:"Hình học", th:"รูปทรง", in:"Bangun" },
sk_measure: { ko:"측정", en:"Measurement", ja:"そくてい", zh:"测量", es:"Medida", fr:"Mesure", de:"Messen", pt:"Medida", ru:"Измерения", vi:"Đo lường", th:"การวัด", in:"Pengukuran" },
sk_data: { ko:"자료와 확률", en:"Data & probability", ja:"データとかくりつ", zh:"数据与概率", es:"Datos y probabilidad", fr:"Données et probabilités", de:"Daten und Wahrscheinlichkeit", pt:"Dados e probabilidade", ru:"Данные и вероятность", vi:"Dữ liệu và xác suất", th:"ข้อมูลและความน่าจะเป็น", in:"Data dan peluang" },
sk_word: { ko:"문장제", en:"Word problems", ja:"ぶんしょうだい", zh:"应用题", es:"Problemas verbales", fr:"Problèmes", de:"Textaufgaben", pt:"Problemas", ru:"Текстовые задачи", vi:"Toán đố", th:"โจทย์ปัญหา", in:"Soal cerita" },
rk_seed: { ko:"알 속의 새싹", en:"Sprout in the egg", ja:"たまごの中のめ", zh:"蛋里的嫩芽", es:"Brote en el huevo", fr:"Pousse dans l'œuf", de:"Keim im Ei", pt:"Broto no ovo", ru:"Росток в яйце", vi:"Mầm trong trứng", th:"หน่ออ่อนในไข่", in:"Tunas dalam telur" },
rk_hatch: { ko:"갓 깬 병아리", en:"Newly hatched chick", ja:"かえったばかりのひよこ", zh:"刚孵出的小鸡", es:"Pollito recién nacido", fr:"Poussin fraîchement éclos", de:"Frisch geschlüpftes Küken", pt:"Pintinho recém-nascido", ru:"Только вылупившийся цыплёнок", vi:"Gà con mới nở", th:"ลูกเจี๊ยบเพิ่งฟัก", in:"Anak ayam baru menetas" },
rk_piyak: { ko:"삐약이", en:"Piyak", ja:"ピヤック", zh:"啾啾", es:"Piyak", fr:"Piyak", de:"Piyak", pt:"Piyak", ru:"Пияк", vi:"Piyak", th:"พียัค", in:"Piyak" },
rk_brave: { ko:"씩씩한 병아리", en:"Brave chick", ja:"げんきなひよこ", zh:"勇敢的小鸡", es:"Pollito valiente", fr:"Poussin courageux", de:"Mutiges Küken", pt:"Pintinho corajoso", ru:"Смелый цыплёнок", vi:"Gà con dũng cảm", th:"ลูกเจี๊ยบผู้กล้า", in:"Anak ayam pemberani" },
rk_sparrow: { ko:"재잘재잘 참새", en:"Chatty sparrow", ja:"おしゃべりすずめ", zh:"叽喳的麻雀", es:"Gorrión parlanchín", fr:"Moineau bavard", de:"Plaudernder Spatz", pt:"Pardal tagarela", ru:"Болтливый воробей", vi:"Chim sẻ líu lo", th:"นกกระจอกช่างคุย", in:"Burung pipit cerewet" },
rk_dove: { ko:"자유로운 비둘기", en:"Free dove", ja:"じゆうなはと", zh:"自由的鸽子", es:"Paloma libre", fr:"Colombe libre", de:"Freie Taube", pt:"Pomba livre", ru:"Свободный голубь", vi:"Bồ câu tự do", th:"นกพิราบอิสระ", in:"Merpati bebas" },
rk_parrot: { ko:"수다쟁이 앵무새", en:"Talkative parrot", ja:"おしゃべりオウム", zh:"话痨鹦鹉", es:"Loro hablador", fr:"Perroquet bavard", de:"Redseliger Papagei", pt:"Papagaio falante", ru:"Говорливый попугай", vi:"Vẹt lắm lời", th:"นกแก้วช่างพูด", in:"Kakaktua cerewet" },
rk_owl: { ko:"지혜로운 부엉이", en:"Wise owl", ja:"かしこいフクロウ", zh:"智慧的猫头鹰", es:"Búho sabio", fr:"Hibou sage", de:"Weise Eule", pt:"Coruja sábia", ru:"Мудрая сова", vi:"Cú thông thái", th:"นกฮูกผู้ชาญฉลาด", in:"Burung hantu bijak" },
rk_eagle: { ko:"하늘의 독수리", en:"Eagle of the sky", ja:"そらのワシ", zh:"天空之鹰", es:"Águila del cielo", fr:"Aigle du ciel", de:"Adler des Himmels", pt:"Águia do céu", ru:"Орёл небес", vi:"Đại bàng trên trời", th:"อินทรีแห่งท้องฟ้า", in:"Elang langit" },
bg_first_lesson: { ko:"첫걸음", en:"First step", ja:"はじめの一歩", zh:"第一步", es:"Primer paso", fr:"Premier pas", de:"Erster Schritt", pt:"Primeiro passo", ru:"Первый шаг", vi:"Bước đầu tiên", th:"ก้าวแรก", in:"Langkah pertama" },
bg_first_lesson_d: { ko:"첫 레슨 완료", en:"Finished your first lesson", ja:"はじめてのレッスンかんりょう", zh:"完成第一课", es:"Completaste tu primera lección", fr:"Première leçon terminée", de:"Erste Lektion geschafft", pt:"Concluiu a primeira lição", ru:"Завершён первый урок", vi:"Hoàn thành bài học đầu tiên", th:"เรียนจบบทแรก", in:"Menyelesaikan pelajaran pertama" },
bg_lessons_10: { ko:"공부벌레", en:"Bookworm", ja:"べんきょうむし", zh:"学习小虫", es:"Ratón de biblioteca", fr:"Rat de bibliothèque", de:"Leseratte", pt:"Ratinho de biblioteca", ru:"Книжный червь", vi:"Mọt sách", th:"หนอนหนังสือ", in:"Kutu buku" },
bg_lessons_10_d: { ko:"레슨 10개 완료", en:"Finished 10 lessons", ja:"レッスン10こかんりょう", zh:"完成10课", es:"Completaste 10 lecciones", fr:"10 leçons terminées", de:"10 Lektionen geschafft", pt:"Concluiu 10 lições", ru:"Пройдено 10 уроков", vi:"Hoàn thành 10 bài học", th:"เรียนจบ 10 บท", in:"Menyelesaikan 10 pelajaran" },
bg_lessons_50: { ko:"모범생", en:"Star student", ja:"もはんせい", zh:"模范生", es:"Estudiante ejemplar", fr:"Élève modèle", de:"Musterschüler", pt:"Aluno exemplar", ru:"Отличник", vi:"Học sinh gương mẫu", th:"นักเรียนตัวอย่าง", in:"Siswa teladan" },
bg_lessons_50_d: { ko:"레슨 50개 완료", en:"Finished 50 lessons", ja:"レッスン50こかんりょう", zh:"完成50课", es:"Completaste 50 lecciones", fr:"50 leçons terminées", de:"50 Lektionen geschafft", pt:"Concluiu 50 lições", ru:"Пройдено 50 уроков", vi:"Hoàn thành 50 bài học", th:"เรียนจบ 50 บท", in:"Menyelesaikan 50 pelajaran" },
bg_lessons_200_d: { ko:"레슨 200개 완료", en:"Finished 200 lessons", ja:"レッスン200こかんりょう", zh:"完成200课", es:"Completaste 200 lecciones", fr:"200 leçons terminées", de:"200 Lektionen geschafft", pt:"Concluiu 200 lições", ru:"Пройдено 200 уроков", vi:"Hoàn thành 200 bài học", th:"เรียนจบ 200 บท", in:"Menyelesaikan 200 pelajaran" },
bg_perfect_10: { ko:"완벽주의", en:"Perfectionist", ja:"かんぺきしゅぎ", zh:"完美主义", es:"Perfeccionista", fr:"Perfectionniste", de:"Perfektionist", pt:"Perfeccionista", ru:"Перфекционист", vi:"Người cầu toàn", th:"ผู้รักความสมบูรณ์แบบ", in:"Perfeksionis" },
bg_perfect_10_d: { ko:"퍼펙트 레슨 10회", en:"10 perfect lessons", ja:"パーフェクトレッスン10かい", zh:"10次满分课程", es:"10 lecciones perfectas", fr:"10 leçons parfaites", de:"10 perfekte Lektionen", pt:"10 lições perfeitas", ru:"10 идеальных уроков", vi:"10 bài học hoàn hảo", th:"เรียนเต็ม 10 บท", in:"10 pelajaran sempurna" },
bg_streak_7: { ko:"일주일 불꽃", en:"One-week flame", ja:"一週間のほのお", zh:"一周火焰", es:"Llama de una semana", fr:"Flamme d'une semaine", de:"Wochenflamme", pt:"Chama de uma semana", ru:"Недельный огонь", vi:"Ngọn lửa một tuần", th:"เปลวไฟหนึ่งสัปดาห์", in:"Api sepekan" },
bg_streak_7_d: { ko:"7일 연속 학습", en:"Studied 7 days in a row", ja:"7日れんぞくがくしゅう", zh:"连续学习7天", es:"Estudiaste 7 días seguidos", fr:"7 jours d'affilée", de:"7 Tage in Folge gelernt", pt:"Estudou 7 dias seguidos", ru:"7 дней подряд", vi:"Học 7 ngày liên tiếp", th:"เรียนต่อเนื่อง 7 วัน", in:"Belajar 7 hari berturut-turut" },
bg_streak_30: { ko:"한달 화산", en:"One-month volcano", ja:"一か月の火山", zh:"一月火山", es:"Volcán de un mes", fr:"Volcan d'un mois", de:"Monatsvulkan", pt:"Vulcão de um mês", ru:"Месячный вулкан", vi:"Núi lửa một tháng", th:"ภูเขาไฟหนึ่งเดือน", in:"Gunung api sebulan" },
bg_streak_30_d: { ko:"30일 연속 학습", en:"Studied 30 days in a row", ja:"30日れんぞくがくしゅう", zh:"连续学习30天", es:"Estudiaste 30 días seguidos", fr:"30 jours d'affilée", de:"30 Tage in Folge gelernt", pt:"Estudou 30 dias seguidos", ru:"30 дней подряд", vi:"Học 30 ngày liên tiếp", th:"เรียนต่อเนื่อง 30 วัน", in:"Belajar 30 hari berturut-turut" },
bg_xp_1000: { ko:"별 헤는 밤", en:"Night of counting stars", ja:"星をかぞえるよる", zh:"数星星的夜晚", es:"Noche de contar estrellas", fr:"Nuit à compter les étoiles", de:"Nacht der Sterne", pt:"Noite de contar estrelas", ru:"Ночь звёзд", vi:"Đêm đếm sao", th:"คืนนับดาว", in:"Malam menghitung bintang" },
bg_xp_1000_d: { ko:"누적 XP 1,000", en:"1,000 XP earned", ja:"るいけいXP 1,000", zh:"累计1,000 XP", es:"1.000 XP acumulados", fr:"1 000 XP cumulés", de:"1.000 XP gesammelt", pt:"1.000 XP acumulados", ru:"Накоплено 1000 XP", vi:"Đạt 1.000 XP", th:"สะสม 1,000 XP", in:"1.000 XP terkumpul" },
bg_xp_5000: { ko:"슈퍼스타", en:"Superstar", ja:"スーパースター", zh:"超级明星", es:"Superestrella", fr:"Superstar", de:"Superstar", pt:"Superestrela", ru:"Суперзвезда", vi:"Siêu sao", th:"ซูเปอร์สตาร์", in:"Superstar" },
bg_xp_5000_d: { ko:"누적 XP 5,000", en:"5,000 XP earned", ja:"るいけいXP 5,000", zh:"累计5,000 XP", es:"5.000 XP acumulados", fr:"5 000 XP cumulés", de:"5.000 XP gesammelt", pt:"5.000 XP acumulados", ru:"Накоплено 5000 XP", vi:"Đạt 5.000 XP", th:"สะสม 5,000 XP", in:"5.000 XP terkumpul" },
bg_placement: { ko:"제자리 찾기", en:"Found your level", ja:"じぶんのばしょさがし", zh:"找到自己的位置", es:"Encontraste tu nivel", fr:"Niveau trouvé", de:"Dein Level gefunden", pt:"Encontrou seu nível", ru:"Уровень определён", vi:"Tìm đúng trình độ", th:"พบระดับของตัวเอง", in:"Menemukan levelmu" },
bg_placement_d: { ko:"레벨테스트 완료", en:"Completed the placement test", ja:"レベルテストかんりょう", zh:"完成分级测试", es:"Completaste la prueba de nivel", fr:"Test de niveau terminé", de:"Einstufungstest gemacht", pt:"Concluiu o teste de nível", ru:"Пройден тест уровня", vi:"Hoàn thành bài kiểm tra trình độ", th:"ทำแบบทดสอบระดับเสร็จ", in:"Menyelesaikan tes penempatan" },
bg_review_50: { ko:"오답 청소부", en:"Mistake sweeper", ja:"まちがいそうじや", zh:"错题清道夫", es:"Barredor de errores", fr:"Balayeur d'erreurs", de:"Fehlerfeger", pt:"Faxineiro de erros", ru:"Уборщик ошибок", vi:"Người dọn lỗi sai", th:"นักกวาดข้อผิด", in:"Penyapu kesalahan" },
bg_review_50_d: { ko:"오답 50개 클리어", en:"Cleared 50 mistakes", ja:"まちがい50こクリア", zh:"攻克50道错题", es:"Superaste 50 errores", fr:"50 erreurs corrigées", de:"50 Fehler erledigt", pt:"Superou 50 erros", ru:"Закрыто 50 ошибок", vi:"Xử lý 50 câu sai", th:"แก้ข้อผิด 50 ข้อ", in:"Menuntaskan 50 kesalahan" },
bg_unit_master: { ko:"유닛 정복자", en:"Unit conqueror", ja:"ユニットせいふくしゃ", zh:"单元征服者", es:"Conquistador de unidades", fr:"Conquérant d'unités", de:"Einheiten-Eroberer", pt:"Conquistador de unidades", ru:"Покоритель разделов", vi:"Người chinh phục chuyên đề", th:"ผู้พิชิตหน่วยการเรียน", in:"Penakluk unit" },
bg_unit_master_d: { ko:"한 트랙의 유닛 5개 완료", en:"Finished 5 units in one track", ja:"1つのコースでユニット5こかんりょう", zh:"在一个课程中完成5个单元", es:"Completaste 5 unidades de un curso", fr:"5 unités terminées dans un parcours", de:"5 Einheiten in einem Kurs geschafft", pt:"Concluiu 5 unidades de um curso", ru:"Пройдено 5 разделов одного курса", vi:"Hoàn thành 5 chuyên đề trong một khóa", th:"เรียนจบ 5 หน่วยในหลักสูตรเดียว", in:"Menyelesaikan 5 unit dalam satu jalur" },
bg_goal_first: { ko:"목표 달성", en:"Goal reached", ja:"もくひょうたっせい", zh:"达成目标", es:"Meta lograda", fr:"Objectif atteint", de:"Ziel erreicht", pt:"Meta alcançada", ru:"Цель достигнута", vi:"Đạt mục tiêu", th:"บรรลุเป้าหมาย", in:"Target tercapai" },
bg_goal_first_d: { ko:"오늘의 목표 첫 달성", en:"Met a daily goal for the first time", ja:"きょうのもくひょうをはじめてたっせい", zh:"首次达成每日目标", es:"Cumpliste una meta diaria por primera vez", fr:"Premier objectif quotidien atteint", de:"Erstes Tagesziel erreicht", pt:"Cumpriu uma meta diária pela primeira vez", ru:"Впервые достигнута дневная цель", vi:"Lần đầu đạt mục tiêu ngày", th:"บรรลุเป้าหมายรายวันครั้งแรก", in:"Pertama kali mencapai target harian" },
bg_goal_10: { ko:"목표 사냥꾼", en:"Goal hunter", ja:"もくひょうハンター", zh:"目标猎人", es:"Cazador de metas", fr:"Chasseur d'objectifs", de:"Ziel-Jäger", pt:"Caçador de metas", ru:"Охотник за целями", vi:"Thợ săn mục tiêu", th:"นักล่าเป้าหมาย", in:"Pemburu target" },
bg_goal_10_d: { ko:"일일 목표 10번 달성", en:"Met daily goals 10 times", ja:"1日のもくひょうを10かいたっせい", zh:"达成每日目标10次", es:"Cumpliste metas diarias 10 veces", fr:"10 objectifs quotidiens atteints", de:"10-mal das Tagesziel erreicht", pt:"Cumpriu metas diárias 10 vezes", ru:"Дневная цель достигнута 10 раз", vi:"Đạt mục tiêu ngày 10 lần", th:"บรรลุเป้าหมายรายวัน 10 ครั้ง", in:"Mencapai target harian 10 kali" },
bg_m_calc: { ko:"계산왕", en:"Calculation king", ja:"けいさん王", zh:"计算王", es:"Rey del cálculo", fr:"Roi du calcul", de:"Rechenkönig", pt:"Rei do cálculo", ru:"Король вычислений", vi:"Vua tính toán", th:"ราชาการคำนวณ", in:"Raja berhitung" },
bg_m_shape: { ko:"도형 박사", en:"Shape doctor", ja:"ずけいはかせ", zh:"图形博士", es:"Doctor de las figuras", fr:"Docteur des formes", de:"Formen-Doktor", pt:"Doutor das figuras", ru:"Доктор фигур", vi:"Tiến sĩ hình học", th:"ด็อกเตอร์รูปทรง", in:"Doktor bangun" },
bg_m_word: { ko:"문장제 해결사", en:"Word problem solver", ja:"ぶんしょうだいかいけつし", zh:"应用题解决者", es:"Solucionador de problemas", fr:"Résolveur de problèmes", de:"Textaufgaben-Löser", pt:"Solucionador de problemas", ru:"Решатель задач", vi:"Người giải toán đố", th:"นักแก้โจทย์ปัญหา", in:"Pemecah soal cerita" },
bg_m_all: { ko:"수학 만능", en:"Math all-rounder", ja:"さんすうばんのう", zh:"数学全能", es:"Todoterreno matemático", fr:"Touche-à-tout des maths", de:"Mathe-Allrounder", pt:"Craque em matemática", ru:"Универсал по математике", vi:"Toàn năng toán học", th:"เก่งรอบด้านคณิตศาสตร์", in:"Serba bisa matematika" },

// ---------- 영어 실력 영역 ----------
sk_listen: { ko:"듣기", en:"Listening", ja:"リスニング", zh:"听力", es:"Escucha", fr:"Écoute", de:"Hören", pt:"Escuta", ru:"Аудирование", vi:"Nghe", th:"การฟัง", in:"Menyimak" },
sk_speak: { ko:"말하기", en:"Speaking", ja:"スピーキング", zh:"口语", es:"Habla", fr:"Expression orale", de:"Sprechen", pt:"Fala", ru:"Говорение", vi:"Nói", th:"การพูด", in:"Berbicara" },
sk_write: { ko:"쓰기", en:"Writing", ja:"ライティング", zh:"写作", es:"Escritura", fr:"Écriture", de:"Schreiben", pt:"Escrita", ru:"Письмо", vi:"Viết", th:"การเขียน", in:"Menulis" },
sk_grammar: { ko:"문법", en:"Grammar", ja:"ぶんぽう", zh:"语法", es:"Gramática", fr:"Grammaire", de:"Grammatik", pt:"Gramática", ru:"Грамматика", vi:"Ngữ pháp", th:"ไวยากรณ์", in:"Tata bahasa" },
sk_read: { ko:"독해", en:"Reading", ja:"どっかい", zh:"阅读", es:"Lectura", fr:"Lecture", de:"Lesen", pt:"Leitura", ru:"Чтение", vi:"Đọc hiểu", th:"การอ่าน", in:"Membaca" },
sk_vocab: { ko:"어휘", en:"Vocabulary", ja:"ごい", zh:"词汇", es:"Vocabulario", fr:"Vocabulaire", de:"Wortschatz", pt:"Vocabulário", ru:"Словарный запас", vi:"Từ vựng", th:"คำศัพท์", in:"Kosakata" },

// ---------- 칭호 (마지막 하나만 수학과 다르다) ----------
rk_master: { ko:"영어 마스터", en:"English master", ja:"えいごマスター", zh:"英语大师", es:"Maestro del inglés", fr:"Maître d'anglais", de:"Englisch-Meister", pt:"Mestre do inglês", ru:"Мастер английского", vi:"Bậc thầy tiếng Anh", th:"ยอดฝีมือภาษาอังกฤษ", in:"Master bahasa Inggris" },

// ---------- 영어 전용 배지 ----------
bg_lessons_200: { ko:"영어왕", en:"English king", ja:"えいごおう", zh:"英语王", es:"Rey del inglés", fr:"Roi de l'anglais", de:"Englisch-König", pt:"Rei do inglês", ru:"Король английского", vi:"Vua tiếng Anh", th:"ราชาภาษาอังกฤษ", in:"Raja bahasa Inggris" },
bg_ear: { ko:"귀가 트였다", en:"Open ears", ja:"みみが ひらいた", zh:"耳朵开窍了", es:"Oído despierto", fr:"Oreille affûtée", de:"Offene Ohren", pt:"Ouvido apurado", ru:"Слух открылся", vi:"Tai đã thông", th:"หูเปิดแล้ว", in:"Telinga terbuka" },
bg_ear_d: { ko:"듣기 실력 Lv.5", en:"Listening skill Lv.5", ja:"リスニング Lv.5", zh:"听力 Lv.5", es:"Escucha Lv.5", fr:"Écoute niv.5", de:"Hören Lv.5", pt:"Escuta Lv.5", ru:"Аудирование ур.5", vi:"Kỹ năng nghe Lv.5", th:"ทักษะการฟัง Lv.5", in:"Menyimak Lv.5" },
bg_mouth: { ko:"입이 트였다", en:"Talking freely", ja:"くちが ひらいた", zh:"嘴巴开窍了", es:"Lengua suelta", fr:"Langue déliée", de:"Redefluss", pt:"Língua solta", ru:"Речь пошла", vi:"Miệng đã thông", th:"พูดคล่องแล้ว", in:"Lancar bicara" },
bg_mouth_d: { ko:"말하기 실력 Lv.5", en:"Speaking skill Lv.5", ja:"スピーキング Lv.5", zh:"口语 Lv.5", es:"Habla Lv.5", fr:"Expression orale niv.5", de:"Sprechen Lv.5", pt:"Fala Lv.5", ru:"Говорение ур.5", vi:"Kỹ năng nói Lv.5", th:"ทักษะการพูด Lv.5", in:"Berbicara Lv.5" },
bg_hand: { ko:"손이 풀렸다", en:"Nimble hands", ja:"てが すらすら", zh:"手感来了", es:"Manos sueltas", fr:"Main déliée", de:"Lockere Hand", pt:"Mão solta", ru:"Рука расписалась", vi:"Tay đã quen", th:"มือคล่องแล้ว", in:"Tangan lentur" },
bg_hand_d: { ko:"쓰기 실력 Lv.5", en:"Writing skill Lv.5", ja:"ライティング Lv.5", zh:"写作 Lv.5", es:"Escritura Lv.5", fr:"Écriture niv.5", de:"Schreiben Lv.5", pt:"Escrita Lv.5", ru:"Письмо ур.5", vi:"Kỹ năng viết Lv.5", th:"ทักษะการเขียน Lv.5", in:"Menulis Lv.5" },
bg_grammar: { ko:"문법 도사", en:"Grammar guru", ja:"ぶんぽうの たつじん", zh:"语法高手", es:"Gurú de la gramática", fr:"As de la grammaire", de:"Grammatik-Guru", pt:"Guru da gramática", ru:"Гуру грамматики", vi:"Cao thủ ngữ pháp", th:"เซียนไวยากรณ์", in:"Ahli tata bahasa" },
bg_grammar_d: { ko:"문법 실력 Lv.5", en:"Grammar skill Lv.5", ja:"ぶんぽう Lv.5", zh:"语法 Lv.5", es:"Gramática Lv.5", fr:"Grammaire niv.5", de:"Grammatik Lv.5", pt:"Gramática Lv.5", ru:"Грамматика ур.5", vi:"Ngữ pháp Lv.5", th:"ไวยากรณ์ Lv.5", in:"Tata bahasa Lv.5" },
bg_all: { ko:"만능 삐약이", en:"All-round chick", ja:"オールマイティ ぴよ", zh:"全能小鸡", es:"Pollito todoterreno", fr:"Poussin complet", de:"Allround-Küken", pt:"Pintinho completo", ru:"Цыплёнок-универсал", vi:"Gà con toàn năng", th:"ลูกเจี๊ยบรอบด้าน", in:"Anak ayam serba bisa" },
bg_all_d: { ko:"영어 모든 영역 Lv.3 이상", en:"All English skills Lv.3+", ja:"えいご ぜんいき Lv.3 いじょう", zh:"英语所有领域 Lv.3 以上", es:"Todas las áreas de inglés Lv.3+", fr:"Toutes les compétences d'anglais niv.3+", de:"Alle Englisch-Bereiche Lv.3+", pt:"Todas as áreas de inglês Lv.3+", ru:"Все области английского ур.3+", vi:"Mọi kỹ năng tiếng Anh Lv.3+", th:"ทุกด้านภาษาอังกฤษ Lv.3 ขึ้นไป", in:"Semua area Inggris Lv.3+" },

// ---------- 수학 배지 설명 (영어 앱은 '수학' 접두어가 붙는다) ----------
bg_m_calc_d: { ko:"수학 계산 실력 Lv.5", en:"Math calculation Lv.5", ja:"さんすうの けいさん Lv.5", zh:"数学计算 Lv.5", es:"Cálculo (mates) Lv.5", fr:"Calcul (maths) niv.5", de:"Mathe-Rechnen Lv.5", pt:"Cálculo (mat.) Lv.5", ru:"Матем. вычисления ур.5", vi:"Tính toán (toán) Lv.5", th:"การคำนวณ (คณิต) Lv.5", in:"Berhitung (mtk) Lv.5" },
bg_m_shape_d: { ko:"수학 도형 실력 Lv.5", en:"Math shapes Lv.5", ja:"さんすうの ずけい Lv.5", zh:"数学图形 Lv.5", es:"Figuras (mates) Lv.5", fr:"Figures (maths) niv.5", de:"Mathe-Formen Lv.5", pt:"Figuras (mat.) Lv.5", ru:"Матем. фигуры ур.5", vi:"Hình học (toán) Lv.5", th:"รูปทรง (คณิต) Lv.5", in:"Bangun (mtk) Lv.5" },
bg_m_word_d: { ko:"수학 문장제 실력 Lv.5", en:"Math word problems Lv.5", ja:"さんすうの ぶんしょうだい Lv.5", zh:"数学应用题 Lv.5", es:"Problemas (mates) Lv.5", fr:"Problèmes (maths) niv.5", de:"Mathe-Textaufgaben Lv.5", pt:"Problemas (mat.) Lv.5", ru:"Текстовые задачи ур.5", vi:"Toán đố Lv.5", th:"โจทย์ปัญหา (คณิต) Lv.5", in:"Soal cerita (mtk) Lv.5" },
bg_m_all_d: { ko:"수학 모든 영역 Lv.3 이상", en:"All math skills Lv.3+", ja:"さんすう ぜんいき Lv.3 いじょう", zh:"数学所有领域 Lv.3 以上", es:"Todas las áreas de mates Lv.3+", fr:"Toutes les compétences de maths niv.3+", de:"Alle Mathe-Bereiche Lv.3+", pt:"Todas as áreas de mat. Lv.3+", ru:"Все области математики ур.3+", vi:"Mọi mảng toán Lv.3+", th:"ทุกด้านคณิต Lv.3 ขึ้นไป", in:"Semua area mtk Lv.3+" },
bg_both: { ko:"두 과목 척척", en:"Double subject star", ja:"りょうかもく バッチリ", zh:"两科都拿手", es:"As de dos materias", fr:"Champion des deux matières", de:"Zwei Fächer top", pt:"Craque nas duas matérias", ru:"Силён в двух предметах", vi:"Giỏi cả hai môn", th:"เก่งทั้งสองวิชา", in:"Jago dua mata pelajaran" },
bg_both_d: { ko:"영어·수학 모두 Lv.3 이상 영역 보유", en:"Lv.3+ area in both English & math", ja:"えいごも さんすうも Lv.3 いじょう", zh:"英语·数学都有 Lv.3 以上领域", es:"Área Lv.3+ en inglés y mates", fr:"Niv.3+ en anglais et en maths", de:"Lv.3+ in Englisch und Mathe", pt:"Área Lv.3+ em inglês e mat.", ru:"Область ур.3+ и в английском, и в математике", vi:"Có mảng Lv.3+ ở cả Anh và Toán", th:"มีด้าน Lv.3+ ทั้งอังกฤษและคณิต", in:"Area Lv.3+ di Inggris dan matematika" },

};
