/**
 * 단계 선택 화면(StageActivity) 카드 제목·부제.
 * 큰 제목 5종은 홈 카드(stage_*)와 같은 키를 쓰고, 영역 이름은 sk_* 를 재사용한다.
 */
module.exports = {

// ---------- 유치원 ----------
st_alpha: { ko:"알파벳 쓰기", en:"Alphabet writing", ja:"アルファベットを かく", zh:"字母书写", es:"Escribir el alfabeto", fr:"Écrire l'alphabet", de:"Alphabet schreiben", pt:"Escrever o alfabeto", ru:"Письмо алфавита", vi:"Viết bảng chữ cái", th:"หัดเขียนตัวอักษร", in:"Menulis alfabet" },
st_alpha_sub: { ko:"A부터 Z까지 손으로 그려요", en:"Trace A to Z by hand", ja:"AからZまで てで かこう", zh:"用手从A写到Z", es:"Traza de la A a la Z a mano", fr:"Trace de A à Z à la main", de:"A bis Z mit der Hand nachfahren", pt:"Trace de A a Z com a mão", ru:"Обведи от A до Z рукой", vi:"Tô từ A đến Z bằng tay", th:"ลากเส้นเขียน A ถึง Z ด้วยมือ", in:"Menjiplak A sampai Z dengan tangan" },
st_first: { ko:"초등영어 첫걸음", en:"First steps in English", ja:"えいごの はじめの いっぽ", zh:"英语第一步", es:"Primeros pasos en inglés", fr:"Premiers pas en anglais", de:"Erste Schritte in Englisch", pt:"Primeiros passos no inglês", ru:"Первые шаги в английском", vi:"Bước đầu tiếng Anh", th:"ก้าวแรกภาษาอังกฤษ", in:"Langkah pertama bahasa Inggris" },
st_first_sub: { ko:"파닉스 · 그림낱말 · 문장", en:"Phonics · Picture words · Sentences", ja:"フォニックス · えたんご · ぶんしょう", zh:"自然拼读 · 图画单词 · 句子", es:"Fonética · Palabras con dibujos · Frases", fr:"Phonétique · Mots illustrés · Phrases", de:"Phonics · Bildwörter · Sätze", pt:"Fonética · Palavras com figuras · Frases", ru:"Фонетика · Слова с картинками · Предложения", vi:"Phonics · Từ có hình · Câu", th:"โฟนิกส์ · คำพร้อมรูป · ประโยค", in:"Fonik · Kata bergambar · Kalimat" },
st_play: { ko:"놀이터", en:"Playground", ja:"あそびば", zh:"游乐场", es:"Zona de juegos", fr:"Aire de jeux", de:"Spielplatz", pt:"Parquinho", ru:"Игровая площадка", vi:"Sân chơi", th:"สนามเด็กเล่น", in:"Taman bermain" },
st_play_sub: { ko:"풍선 터뜨리기 · 담기 · 선 잇기", en:"Pop balloons · Sort · Match lines", ja:"ふうせんわり · いれる · せんつなぎ", zh:"戳气球 · 分类 · 连线", es:"Explota globos · Clasifica · Une líneas", fr:"Éclate les ballons · Trie · Relie", de:"Ballons platzen · Einsortieren · Verbinden", pt:"Estourar balões · Separar · Ligar", ru:"Лопай шары · Сортируй · Соединяй", vi:"Bắn bóng · Phân loại · Nối", th:"เจาะลูกโป่ง · จัดกลุ่ม · ลากเส้นจับคู่", in:"Pecahkan balon · Pilah · Hubungkan" },

// ---------- 초등 ----------
st_elem_course: { ko:"초등영어 코스", en:"Elementary course", ja:"しょうがくえいご コース", zh:"小学英语课程", es:"Curso de primaria", fr:"Cours primaire", de:"Grundschulkurs", pt:"Curso fundamental", ru:"Курс начальной школы", vi:"Khóa tiểu học", th:"คอร์สประถม", in:"Kursus SD" },
st_elem_course_sub: { ko:"알파벳부터 문장까지 놀면서", en:"From ABC to sentences, playfully", ja:"ABCから ぶんしょうまで あそびながら", zh:"从字母到句子，边玩边学", es:"Del abecedario a las frases, jugando", fr:"De l'alphabet aux phrases, en s'amusant", de:"Vom ABC bis zum Satz, spielerisch", pt:"Do ABC às frases, brincando", ru:"От алфавита до предложений — играя", vi:"Từ ABC đến câu, vừa học vừa chơi", th:"จาก ABC ถึงประโยค เรียนแบบสนุก", in:"Dari ABC ke kalimat sambil bermain" },
st_g12: { ko:"기초 · 초등 1~2학년", en:"Basics · Grades 1–2", ja:"きそ · しょう1~2ねん", zh:"基础 · 小学1~2年级", es:"Básico · 1º–2º", fr:"Bases · Années 1–2", de:"Basis · Klasse 1–2", pt:"Básico · 1º–2º ano", ru:"База · 1–2 класс", vi:"Cơ bản · Lớp 1–2", th:"พื้นฐาน · ป.1–2", in:"Dasar · Kelas 1–2" },
st_g12_sub: { ko:"첫 단어와 인사", en:"First words and greetings", ja:"はじめての たんごと あいさつ", zh:"第一批单词和问候", es:"Primeras palabras y saludos", fr:"Premiers mots et salutations", de:"Erste Wörter und Begrüßungen", pt:"Primeiras palavras e cumprimentos", ru:"Первые слова и приветствия", vi:"Từ đầu tiên và lời chào", th:"คำแรกและคำทักทาย", in:"Kata pertama dan salam" },
st_g34: { ko:"기초 · 초등 3~4학년", en:"Basics · Grades 3–4", ja:"きそ · しょう3~4ねん", zh:"基础 · 小学3~4年级", es:"Básico · 3º–4º", fr:"Bases · Années 3–4", de:"Basis · Klasse 3–4", pt:"Básico · 3º–4º ano", ru:"База · 3–4 класс", vi:"Cơ bản · Lớp 3–4", th:"พื้นฐาน · ป.3–4", in:"Dasar · Kelas 3–4" },
st_g34_sub: { ko:"일상 단어와 짧은 문장", en:"Everyday words and short sentences", ja:"にちじょうの たんごと みじかい ぶん", zh:"日常单词和短句", es:"Palabras cotidianas y frases cortas", fr:"Mots du quotidien et phrases courtes", de:"Alltagswörter und kurze Sätze", pt:"Palavras do dia a dia e frases curtas", ru:"Повседневные слова и короткие фразы", vi:"Từ hằng ngày và câu ngắn", th:"คำในชีวิตประจำวันและประโยคสั้น", in:"Kata sehari-hari dan kalimat pendek" },
st_g56: { ko:"기초 · 초등 5~6학년", en:"Basics · Grades 5–6", ja:"きそ · しょう5~6ねん", zh:"基础 · 小学5~6年级", es:"Básico · 5º–6º", fr:"Bases · Années 5–6", de:"Basis · Klasse 5–6", pt:"Básico · 5º–6º ano", ru:"База · 5–6 класс", vi:"Cơ bản · Lớp 5–6", th:"พื้นฐาน · ป.5–6", in:"Dasar · Kelas 5–6" },
st_g56_sub: { ko:"문장 만들기가 익숙해져요", en:"Get comfortable building sentences", ja:"ぶんづくりに なれてくる", zh:"造句越来越熟练", es:"Construir frases se vuelve fácil", fr:"Construire des phrases devient naturel", de:"Sätze bilden wird vertraut", pt:"Montar frases fica natural", ru:"Составлять предложения станет привычно", vi:"Quen dần với việc đặt câu", th:"สร้างประโยคได้คล่องขึ้น", in:"Makin terbiasa menyusun kalimat" },

// ---------- 중·고등 ----------
st_m1: { ko:"기초 · 중학 1학년", en:"Basics · Middle school 1", ja:"きそ · ちゅう1", zh:"基础 · 初一", es:"Básico · Secundaria 1", fr:"Bases · Collège 1", de:"Basis · Mittelstufe 1", pt:"Básico · Ginásio 1", ru:"База · Средняя школа 1", vi:"Cơ bản · Lớp 7", th:"พื้นฐาน · ม.1", in:"Dasar · SMP 1" },
st_m2: { ko:"기초 · 중학 2학년", en:"Basics · Middle school 2", ja:"きそ · ちゅう2", zh:"基础 · 初二", es:"Básico · Secundaria 2", fr:"Bases · Collège 2", de:"Basis · Mittelstufe 2", pt:"Básico · Ginásio 2", ru:"База · Средняя школа 2", vi:"Cơ bản · Lớp 8", th:"พื้นฐาน · ม.2", in:"Dasar · SMP 2" },
st_m3: { ko:"기초 · 중학 3학년", en:"Basics · Middle school 3", ja:"きそ · ちゅう3", zh:"基础 · 初三", es:"Básico · Secundaria 3", fr:"Bases · Collège 3", de:"Basis · Mittelstufe 3", pt:"Básico · Ginásio 3", ru:"База · Средняя школа 3", vi:"Cơ bản · Lớp 9", th:"พื้นฐาน · ม.3", in:"Dasar · SMP 3" },
st_h1: { ko:"기초 · 고등 1학년", en:"Basics · High school 1", ja:"きそ · こう1", zh:"基础 · 高一", es:"Básico · Bachillerato 1", fr:"Bases · Lycée 1", de:"Basis · Oberstufe 1", pt:"Básico · Colegial 1", ru:"База · Старшая школа 1", vi:"Cơ bản · Lớp 10", th:"พื้นฐาน · ม.4", in:"Dasar · SMA 1" },
st_h23: { ko:"기초 · 고등 2~3학년", en:"Basics · High school 2–3", ja:"きそ · こう2~3", zh:"基础 · 高二~高三", es:"Básico · Bachillerato 2–3", fr:"Bases · Lycée 2–3", de:"Basis · Oberstufe 2–3", pt:"Básico · Colegial 2–3", ru:"База · Старшая школа 2–3", vi:"Cơ bản · Lớp 11–12", th:"พื้นฐาน · ม.5–6", in:"Dasar · SMA 2–3" },
st_grammar: { ko:"문법 집중", en:"Grammar focus", ja:"ぶんぽう しゅうちゅう", zh:"语法专项", es:"Enfoque en gramática", fr:"Spécial grammaire", de:"Grammatik-Fokus", pt:"Foco em gramática", ru:"Упор на грамматику", vi:"Chuyên ngữ pháp", th:"เจาะไวยากรณ์", in:"Fokus tata bahasa" },
st_grammar_sub: { ko:"규칙을 확실하게", en:"Nail down the rules", ja:"ルールを しっかり", zh:"把规则学扎实", es:"Domina las reglas", fr:"Maîtrise les règles", de:"Regeln sicher beherrschen", pt:"Domine as regras", ru:"Закрепи правила", vi:"Nắm chắc quy tắc", th:"แม่นกฎให้ชัด", in:"Kuasai aturannya" },
st_reading: { ko:"독해 집중", en:"Reading focus", ja:"どっかい しゅうちゅう", zh:"阅读专项", es:"Enfoque en lectura", fr:"Spécial lecture", de:"Lese-Fokus", pt:"Foco em leitura", ru:"Упор на чтение", vi:"Chuyên đọc hiểu", th:"เจาะการอ่าน", in:"Fokus membaca" },
st_reading_sub: { ko:"지문 읽고 답하기", en:"Read passages and answer", ja:"ぶんしょうを よんで こたえる", zh:"读短文并作答", es:"Lee textos y responde", fr:"Lis des textes et réponds", de:"Texte lesen und antworten", pt:"Leia textos e responda", ru:"Читай тексты и отвечай", vi:"Đọc đoạn văn và trả lời", th:"อ่านเนื้อเรื่องแล้วตอบ", in:"Baca teks lalu jawab" },

// ---------- 성인 ----------
st_adult_mid: { ko:"기초 · 성인 중급", en:"Basics · Adult intermediate", ja:"きそ · おとな ちゅうきゅう", zh:"基础 · 成人中级", es:"Básico · Adulto intermedio", fr:"Bases · Adulte intermédiaire", de:"Basis · Erwachsene Mittelstufe", pt:"Básico · Adulto intermediário", ru:"База · Взрослый средний", vi:"Cơ bản · Người lớn trung cấp", th:"พื้นฐาน · ผู้ใหญ่ระดับกลาง", in:"Dasar · Dewasa menengah" },
st_adult_adv: { ko:"기초 · 고급", en:"Basics · Advanced", ja:"きそ · じょうきゅう", zh:"基础 · 高级", es:"Básico · Avanzado", fr:"Bases · Avancé", de:"Basis · Fortgeschritten", pt:"Básico · Avançado", ru:"База · Продвинутый", vi:"Cơ bản · Nâng cao", th:"พื้นฐาน · ระดับสูง", in:"Dasar · Mahir" },
st_travel: { ko:"일상 · 여행 회화", en:"Daily & travel conversation", ja:"にちじょう · りょこう かいわ", zh:"日常·旅行会话", es:"Conversación diaria y de viaje", fr:"Conversation quotidienne · voyage", de:"Alltags- & Reisegespräche", pt:"Conversação diária e de viagem", ru:"Повседневный и дорожный разговор", vi:"Hội thoại hằng ngày · du lịch", th:"สนทนาในชีวิตประจำวัน · ท่องเที่ยว", in:"Percakapan harian · perjalanan" },
st_travel_sub: { ko:"혼자 여행 가서 써먹기", en:"Use it traveling on your own", ja:"ひとりたびで つかえる", zh:"独自旅行时用得上", es:"Úsalo viajando solo", fr:"À utiliser en voyage solo", de:"Für die Reise allein", pt:"Use viajando sozinho", ru:"Пригодится в самостоятельной поездке", vi:"Dùng khi du lịch một mình", th:"ใช้ได้ตอนเที่ยวคนเดียว", in:"Dipakai saat bepergian sendiri" },
st_toeic: { ko:"토익", en:"TOEIC", ja:"TOEIC", zh:"托业", es:"TOEIC", fr:"TOEIC", de:"TOEIC", pt:"TOEIC", ru:"TOEIC", vi:"TOEIC", th:"TOEIC", in:"TOEIC" },
st_toeic_sub: { ko:"파트별 실전 연습", en:"Practice by part, test style", ja:"パートべつ じっせん れんしゅう", zh:"分部分实战练习", es:"Práctica real por partes", fr:"Entraînement réel par partie", de:"Praxisübung nach Teilen", pt:"Prática real por partes", ru:"Практика по частям теста", vi:"Luyện thực chiến theo phần", th:"ฝึกจริงทีละพาร์ต", in:"Latihan nyata per bagian" },
st_toefl: { ko:"토플", en:"TOEFL", ja:"TOEFL", zh:"托福", es:"TOEFL", fr:"TOEFL", de:"TOEFL", pt:"TOEFL", ru:"TOEFL", vi:"TOEFL", th:"TOEFL", in:"TOEFL" },
st_toefl_sub: { ko:"아카데믹 영어", en:"Academic English", ja:"アカデミック えいご", zh:"学术英语", es:"Inglés académico", fr:"Anglais académique", de:"Akademisches Englisch", pt:"Inglês acadêmico", ru:"Академический английский", vi:"Tiếng Anh học thuật", th:"อังกฤษเชิงวิชาการ", in:"Inggris akademik" },

// ---------- 영역별 부제 ----------
st_listen_sub: { ko:"귀가 뚫리는 연습", en:"Train your ears", ja:"みみを きたえる れんしゅう", zh:"练出好耳朵", es:"Entrena el oído", fr:"Entraîne ton oreille", de:"Ohren trainieren", pt:"Treine o ouvido", ru:"Тренируй слух", vi:"Luyện đôi tai", th:"ฝึกหูให้เฉียบ", in:"Latih telingamu" },
st_speak_sub: { ko:"소리 내어 따라 하기", en:"Repeat out loud", ja:"こえに だして まねする", zh:"大声跟读", es:"Repite en voz alta", fr:"Répète à voix haute", de:"Laut nachsprechen", pt:"Repita em voz alta", ru:"Повторяй вслух", vi:"Đọc to theo mẫu", th:"พูดตามออกเสียง", in:"Ulangi dengan suara keras" },
st_write_sub: { ko:"받아쓰기와 영작", en:"Dictation and writing", ja:"かきとりと えいさくぶん", zh:"听写和写作", es:"Dictado y redacción", fr:"Dictée et rédaction", de:"Diktat und Schreiben", pt:"Ditado e escrita", ru:"Диктант и письмо", vi:"Chính tả và viết câu", th:"เขียนตามคำบอกและแต่งประโยค", in:"Dikte dan menulis" },
st_gram_sub: { ko:"규칙 다지기", en:"Build solid rules", ja:"ルールを かためる", zh:"打牢规则", es:"Afianza las reglas", fr:"Consolide les règles", de:"Regeln festigen", pt:"Firme as regras", ru:"Закрепляй правила", vi:"Củng cố quy tắc", th:"ปูพื้นกฎให้แน่น", in:"Perkuat aturan" },
st_read_sub: { ko:"읽고 이해하기", en:"Read and understand", ja:"よんで りかいする", zh:"读懂文章", es:"Lee y comprende", fr:"Lis et comprends", de:"Lesen und verstehen", pt:"Leia e compreenda", ru:"Читай и понимай", vi:"Đọc và hiểu", th:"อ่านแล้วเข้าใจ", in:"Baca dan pahami" },

// ---------- 진행률 ----------
stage_progress: { ko:"%1$d / %2$d 레슨", en:"%1$d / %2$d lessons", ja:"%1$d / %2$d レッスン", zh:"%1$d / %2$d 课", es:"%1$d / %2$d lecciones", fr:"%1$d / %2$d leçons", de:"%1$d / %2$d Lektionen", pt:"%1$d / %2$d lições", ru:"%1$d / %2$d уроков", vi:"%1$d / %2$d bài", th:"%1$d / %2$d บทเรียน", in:"%1$d / %2$d pelajaran" },

};
